In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
a=pd.read_excel('/content/ecommerce_uncleaned_5000.xlsx')
a

,Order_ID,Customer_ID,Product_ID,Product_Name,Order_Amount,Payment_Mode,Order_Date,Shipping_Address,Quantity,Email,...,Discount,Delivery_Time,Status,Shipping_Fee,Tracking_Number,Billing_Address,Delivery_Date,Price,Category,temp_notes
0,101126,1179,102,Camera,73226.194787,ccard,10/12/23,Delhi,5.0,fmflokr@gmail.com,...,20,5,Pending,150,NaN,Bengaluru,13-08-2020,30950.579179,Fashion,temp
1,100252,1088,58,Headphones,-50.000000,COD,02/09/20,NaN,4.0,NaN,...,50,1,Cancelled,50,TRK4890,Chennai,2024/01/24,47454.499755,Fashion,temp
2,100776,1089,62,Mobile,0.000000,ccard,15/02/20,Delhi,4.0,oyjbadm@hotmail.com,...,50,2,Pending,150,TRK8989,Delhi,2024/09/15,22597.755842,Fashion,temp
3,100995,1013,104,Camera,0.000000,UPI,01-06-2024,Hyderabad,4.0,itngklv@gmail.com,...,5,-3,delivred,150,TRK9684,Chennai,25-08-2023,3912.622055,Accessories,note1
4,101367,1128,145,Camera,81564.596703,Debit Card,25/05/24,Hyderabad,3.0,srkahlm@yahoo.com,...,50,1,delivred,100,NaN,Delhi,2024/09/20,16394.129437,Accessories,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,100718,1104,182,Laptop,51688.683670,Debit Card,2022/08/01,NaN,2.0,tmzrseh@hotmail.com,...,10,1,Pending,150,TRK1383,Bengaluru,22-06-2024,36912.237971,Electronics,NaN
4996,101311,1188,133,Watch,78621.264474,ccard,2021/10/07,Bengaluru,3.0,ryirggj@gmal.com,...,10,-3,delivred,50,TRK6102,Delhi,01-08-2024,23932.133884,Fashion,-
4997,101034,1048,134,Mobile,0.000000,upiid,2022/11/05,Chennai,5.0,orfjbtv@gmail.com,...,10,2,delivred,-20,TRK7161,Mumbai,28-03-2024,19231.261729,Accessories,note1
4998,101287,1002,118,Camera,0.000000,ccard,24-01-2020,Mumbai,3.0,gpgdqxx@yahoo.com,...,10,5,Delivered,150,NaN,Delhi,2022/07/25,40857.577482,Accessories,note1
4999,100264,1066,19,Watch,-50.000000,cashh,2021/06/17,Chennai,-2.0,NaN,...,95,5,delivred,100,TRK5760,Chennai,2019/05/07,18855.669634,Fashion,note1

In [ ]:
a.columns

Index(['Order_ID', 'Customer_ID', 'Product_ID', 'Product_Name', 'Order_Amount',
       'Payment_Mode', 'Order_Date', 'Shipping_Address', 'Quantity', 'Email',
       'Country', 'City', 'Discount', 'Delivery_Time', 'Status',
       'Shipping_Fee', 'Tracking_Number', 'Billing_Address', 'Delivery_Date',
       'Price', 'Category', 'temp_notes'],
      dtype='object')

A.Duplicates & Missing Values

1.	Identify and remove duplicate rows in the e-commerce dataset.

In [ ]:
a.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
4995    False
4996    False
4997    False
4998    False
4999    False
Length: 5000, dtype: bool

2.	Identify duplicate Order_ID values and remove them

In [ ]:
#Duplicate Order_ID and remove them
a.duplicated(subset='Order_ID').sum()

np.int64(3154)

In [ ]:
a.drop_duplicates(subset='Order_ID',inplace=True)
a

,Order_ID,Customer_ID,Product_ID,Product_Name,Order_Amount,Payment_Mode,Order_Date,Shipping_Address,Quantity,Email,...,Discount,Delivery_Time,Status,Shipping_Fee,Tracking_Number,Billing_Address,Delivery_Date,Price,Category,temp_notes
0,101126,1179,102,Camera,7.322619e+04,ccard,10/12/23,Delhi,5.0,fmflokr@gmail.com,...,20,5,Pending,150,NaN,Bengaluru,13-08-2020,30950.579179,Fashion,temp
1,100252,1088,58,Headphones,-5.000000e+01,COD,02/09/20,NaN,4.0,NaN,...,50,1,Cancelled,50,TRK4890,Chennai,2024/01/24,47454.499755,Fashion,temp
2,100776,1089,62,Mobile,0.000000e+00,ccard,15/02/20,Delhi,4.0,oyjbadm@hotmail.com,...,50,2,Pending,150,TRK8989,Delhi,2024/09/15,22597.755842,Fashion,temp
3,100995,1013,104,Camera,0.000000e+00,UPI,01-06-2024,Hyderabad,4.0,itngklv@gmail.com,...,5,-3,delivred,150,TRK9684,Chennai,25-08-2023,3912.622055,Accessories,note1
4,101367,1128,145,Camera,8.156460e+04,Debit Card,25/05/24,Hyderabad,3.0,srkahlm@yahoo.com,...,50,1,delivred,100,NaN,Delhi,2024/09/20,16394.129437,Accessories,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4951,100818,1176,151,Watch,2.000000e+06,Credit Card,20/10/22,Mumbai,-2.0,mvxanjp@gmail.com,...,20,5,Delivered,-20,TRK9669,Mumbai,07-07-2019,28892.278292,Accessories,note1
4952,101609,1018,77,Shoes,-5.000000e+01,upiid,12/01/20,Bengaluru,5.0,xfryyqf@gmal.com,...,5,-3,delivred,50,NaN,Mumbai,2021/02/16,16199.058547,Electronics,-
4982,101160,1139,67,Laptop,2.000000e+06,ccard,2021/10/12,Delhi,2.0,umxsowu@yahoo.com,...,20,-3,pendng,50,NaN,Bengaluru,05-05-2023,25562.242481,Fashion,temp
4984,100832,1064,151,Mobile,8.000390e+04,ccard,25-09-2021,Chennai,5.0,hzggukg@gmal.com,...,5,3,delivred,50,TRK1565,Chennai,23/12/21,29784.570278,Accessories,-
4987,101129,1164,17,Laptop,0.000000e+00,upiid,12/09/19,Hyderabad,1.0,djpflcp@gmail.com,...,50,1,Delivered,-20,NaN,Bengaluru,2020/06/14,206.415472,Accessories,-

In [ ]:
a.duplicated(subset='Order_ID').sum()

np.int64(0)

3.	Detect duplicate Customer_IDs with different emails or addresses

In [ ]:
#Duplicate customer_ID's with diff Email or Addresses
a.groupby('Customer_ID')[['Email','Shipping_Address','Billing_Address']].nunique()

             Email  Shipping_Address  Billing_Address
Customer_ID
1000             6                 3                4
1001             8                 4                4
1002            11                 4                4
1003            11                 4                4
1004            12                 5                4
...            ...               ...              ...
1195             7                 3                3
1196             8                 4                4
1197             5                 4                2
1198            10                 4                4
1199             7                 4                4

[200 rows x 3 columns]

In [ ]:
a.Customer_ID.nunique()

200

4.	Fill missing Product_Name with "Unknown Product".

In [ ]:
a['Product_Name']=a['Product_Name'].fillna('Unknown_Name')
a

,Order_ID,Customer_ID,Product_ID,Product_Name,Order_Amount,Payment_Mode,Order_Date,Shipping_Address,Quantity,Email,...,Discount,Delivery_Time,Status,Shipping_Fee,Tracking_Number,Billing_Address,Delivery_Date,Price,Category,temp_notes
0,101126,1179,102,Camera,7.322619e+04,ccard,10/12/23,Delhi,5.0,fmflokr@gmail.com,...,20,5,Pending,150,NaN,Bengaluru,13-08-2020,30950.579179,Fashion,temp
1,100252,1088,58,Headphones,-5.000000e+01,COD,02/09/20,NaN,4.0,NaN,...,50,1,Cancelled,50,TRK4890,Chennai,2024/01/24,47454.499755,Fashion,temp
2,100776,1089,62,Mobile,0.000000e+00,ccard,15/02/20,Delhi,4.0,oyjbadm@hotmail.com,...,50,2,Pending,150,TRK8989,Delhi,2024/09/15,22597.755842,Fashion,temp
3,100995,1013,104,Camera,0.000000e+00,UPI,01-06-2024,Hyderabad,4.0,itngklv@gmail.com,...,5,-3,delivred,150,TRK9684,Chennai,25-08-2023,3912.622055,Accessories,note1
4,101367,1128,145,Camera,8.156460e+04,Debit Card,25/05/24,Hyderabad,3.0,srkahlm@yahoo.com,...,50,1,delivred,100,NaN,Delhi,2024/09/20,16394.129437,Accessories,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4951,100818,1176,151,Watch,2.000000e+06,Credit Card,20/10/22,Mumbai,-2.0,mvxanjp@gmail.com,...,20,5,Delivered,-20,TRK9669,Mumbai,07-07-2019,28892.278292,Accessories,note1
4952,101609,1018,77,Shoes,-5.000000e+01,upiid,12/01/20,Bengaluru,5.0,xfryyqf@gmal.com,...,5,-3,delivred,50,NaN,Mumbai,2021/02/16,16199.058547,Electronics,-
4982,101160,1139,67,Laptop,2.000000e+06,ccard,2021/10/12,Delhi,2.0,umxsowu@yahoo.com,...,20,-3,pendng,50,NaN,Bengaluru,05-05-2023,25562.242481,Fashion,temp
4984,100832,1064,151,Mobile,8.000390e+04,ccard,25-09-2021,Chennai,5.0,hzggukg@gmal.com,...,5,3,delivred,50,TRK1565,Chennai,23/12/21,29784.570278,Accessories,-
4987,101129,1164,17,Laptop,0.000000e+00,upiid,12/09/19,Hyderabad,1.0,djpflcp@gmail.com,...,50,1,Delivered,-20,NaN,Bengaluru,2020/06/14,206.415472,Accessories,-

5.	Fill missing Order_Amount values with median amount per product

In [ ]:
s=a['Order_Amount'].median()
s

0.0

In [ ]:
a['Order_Amount'].fillna(a['Order_Amount'].median(),inplace=True)
a

/tmp/ipykernel_2327/3628352339.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  a['Order_Amount'].fillna(a['Order_Amount'].median(),inplace=True)

,Order_ID,Customer_ID,Product_ID,Product_Name,Order_Amount,Payment_Mode,Order_Date,Shipping_Address,Quantity,Email,...,Discount,Delivery_Time,Status,Shipping_Fee,Tracking_Number,Billing_Address,Delivery_Date,Price,Category,temp_notes
0,101126,1179,102,Camera,7.322619e+04,ccard,10/12/23,Delhi,5.0,fmflokr@gmail.com,...,20,5,Pending,150,NaN,Bengaluru,13-08-2020,30950.579179,Fashion,temp
1,100252,1088,58,Headphones,-5.000000e+01,COD,02/09/20,NaN,4.0,NaN,...,50,1,Cancelled,50,TRK4890,Chennai,2024/01/24,47454.499755,Fashion,temp
2,100776,1089,62,Mobile,0.000000e+00,ccard,15/02/20,Delhi,4.0,oyjbadm@hotmail.com,...,50,2,Pending,150,TRK8989,Delhi,2024/09/15,22597.755842,Fashion,temp
3,100995,1013,104,Camera,0.000000e+00,UPI,01-06-2024,Hyderabad,4.0,itngklv@gmail.com,...,5,-3,delivred,150,TRK9684,Chennai,25-08-2023,3912.622055,Accessories,note1
4,101367,1128,145,Camera,8.156460e+04,Debit Card,25/05/24,Hyderabad,3.0,srkahlm@yahoo.com,...,50,1,delivred,100,NaN,Delhi,2024/09/20,16394.129437,Accessories,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4951,100818,1176,151,Watch,2.000000e+06,Credit Card,20/10/22,Mumbai,-2.0,mvxanjp@gmail.com,...,20,5,Delivered,-20,TRK9669,Mumbai,07-07-2019,28892.278292,Accessories,note1
4952,101609,1018,77,Shoes,-5.000000e+01,upiid,12/01/20,Bengaluru,5.0,xfryyqf@gmal.com,...,5,-3,delivred,50,NaN,Mumbai,2021/02/16,16199.058547,Electronics,-
4982,101160,1139,67,Laptop,2.000000e+06,ccard,2021/10/12,Delhi,2.0,umxsowu@yahoo.com,...,20,-3,pendng,50,NaN,Bengaluru,05-05-2023,25562.242481,Fashion,temp
4984,100832,1064,151,Mobile,8.000390e+04,ccard,25-09-2021,Chennai,5.0,hzggukg@gmal.com,...,5,3,delivred,50,TRK1565,Chennai,23/12/21,29784.570278,Accessories,-
4987,101129,1164,17,Laptop,0.000000e+00,upiid,12/09/19,Hyderabad,1.0,djpflcp@gmail.com,...,50,1,Delivered,-20,NaN,Bengaluru,2020/06/14,206.415472,Accessories,-

6.	Fill missing Payment_Mode with "Unknown".

In [ ]:
a['Payment_Mode'].isnull().sum()

np.int64(0)

7.	Fill missing Order_Date with NaT or inferred date from other fields.

In [ ]:
a['Order_Date'].isnull().sum()

np.int64(172)

In [ ]:
a['Order_Date'] = pd.to_datetime(a['Order_Date'], errors='coerce')
a['Order_Date'] = a['Order_Date'].fillna(pd.NaT)

/tmp/ipykernel_2327/2061544.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  a['Order_Date'] = pd.to_datetime(a['Order_Date'], errors='coerce')

In [ ]:
a

,Order_ID,Customer_ID,Product_ID,Product_Name,Order_Amount,Payment_Mode,Order_Date,Shipping_Address,Quantity,Email,...,Discount,Delivery_Time,Status,Shipping_Fee,Tracking_Number,Billing_Address,Delivery_Date,Price,Category,temp_notes
0,101126,1179,102,Camera,7.322619e+04,ccard,2023-10-12,Delhi,5.0,fmflokr@gmail.com,...,20,5,Pending,150,NaN,Bengaluru,13-08-2020,30950.579179,Fashion,temp
1,100252,1088,58,Headphones,-5.000000e+01,COD,2020-02-09,NaN,4.0,NaN,...,50,1,Cancelled,50,TRK4890,Chennai,2024/01/24,47454.499755,Fashion,temp
2,100776,1089,62,Mobile,0.000000e+00,ccard,2020-02-15,Delhi,4.0,oyjbadm@hotmail.com,...,50,2,Pending,150,TRK8989,Delhi,2024/09/15,22597.755842,Fashion,temp
3,100995,1013,104,Camera,0.000000e+00,UPI,2024-01-06,Hyderabad,4.0,itngklv@gmail.com,...,5,-3,delivred,150,TRK9684,Chennai,25-08-2023,3912.622055,Accessories,note1
4,101367,1128,145,Camera,8.156460e+04,Debit Card,2024-05-25,Hyderabad,3.0,srkahlm@yahoo.com,...,50,1,delivred,100,NaN,Delhi,2024/09/20,16394.129437,Accessories,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4951,100818,1176,151,Watch,2.000000e+06,Credit Card,2022-10-20,Mumbai,-2.0,mvxanjp@gmail.com,...,20,5,Delivered,-20,TRK9669,Mumbai,07-07-2019,28892.278292,Accessories,note1
4952,101609,1018,77,Shoes,-5.000000e+01,upiid,2020-12-01,Bengaluru,5.0,xfryyqf@gmal.com,...,5,-3,delivred,50,NaN,Mumbai,2021/02/16,16199.058547,Electronics,-
4982,101160,1139,67,Laptop,2.000000e+06,ccard,2021-10-12,Delhi,2.0,umxsowu@yahoo.com,...,20,-3,pendng,50,NaN,Bengaluru,05-05-2023,25562.242481,Fashion,temp
4984,100832,1064,151,Mobile,8.000390e+04,ccard,2021-09-25,Chennai,5.0,hzggukg@gmal.com,...,5,3,delivred,50,TRK1565,Chennai,23/12/21,29784.570278,Accessories,-
4987,101129,1164,17,Laptop,0.000000e+00,upiid,2019-12-09,Hyderabad,1.0,djpflcp@gmail.com,...,50,1,Delivered,-20,NaN,Bengaluru,2020/06/14,206.415472,Accessories,-

8.	Replace missing Shipping_Address with "Unspecified".

In [ ]:
a['Shipping_Address']=a['Shipping_Address'].fillna('unspecified')
a

,Order_ID,Customer_ID,Product_ID,Product_Name,Order_Amount,Payment_Mode,Order_Date,Shipping_Address,Quantity,Email,...,Discount,Delivery_Time,Status,Shipping_Fee,Tracking_Number,Billing_Address,Delivery_Date,Price,Category,temp_notes
0,101126,1179,102,Camera,7.322619e+04,ccard,2023-10-12,Delhi,5.0,fmflokr@gmail.com,...,20,5,Pending,150,NaN,Bengaluru,13-08-2020,30950.579179,Fashion,temp
1,100252,1088,58,Headphones,-5.000000e+01,COD,2020-02-09,unspecified,4.0,NaN,...,50,1,Cancelled,50,TRK4890,Chennai,2024/01/24,47454.499755,Fashion,temp
2,100776,1089,62,Mobile,0.000000e+00,ccard,2020-02-15,Delhi,4.0,oyjbadm@hotmail.com,...,50,2,Pending,150,TRK8989,Delhi,2024/09/15,22597.755842,Fashion,temp
3,100995,1013,104,Camera,0.000000e+00,UPI,2024-01-06,Hyderabad,4.0,itngklv@gmail.com,...,5,-3,delivred,150,TRK9684,Chennai,25-08-2023,3912.622055,Accessories,note1
4,101367,1128,145,Camera,8.156460e+04,Debit Card,2024-05-25,Hyderabad,3.0,srkahlm@yahoo.com,...,50,1,delivred,100,NaN,Delhi,2024/09/20,16394.129437,Accessories,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4951,100818,1176,151,Watch,2.000000e+06,Credit Card,2022-10-20,Mumbai,-2.0,mvxanjp@gmail.com,...,20,5,Delivered,-20,TRK9669,Mumbai,07-07-2019,28892.278292,Accessories,note1
4952,101609,1018,77,Shoes,-5.000000e+01,upiid,2020-12-01,Bengaluru,5.0,xfryyqf@gmal.com,...,5,-3,delivred,50,NaN,Mumbai,2021/02/16,16199.058547,Electronics,-
4982,101160,1139,67,Laptop,2.000000e+06,ccard,2021-10-12,Delhi,2.0,umxsowu@yahoo.com,...,20,-3,pendng,50,NaN,Bengaluru,05-05-2023,25562.242481,Fashion,temp
4984,100832,1064,151,Mobile,8.000390e+04,ccard,2021-09-25,Chennai,5.0,hzggukg@gmal.com,...,5,3,delivred,50,TRK1565,Chennai,23/12/21,29784.570278,Accessories,-
4987,101129,1164,17,Laptop,0.000000e+00,upiid,2019-12-09,Hyderabad,1.0,djpflcp@gmail.com,...,50,1,Delivered,-20,NaN,Bengaluru,2020/06/14,206.415472,Accessories,-

9.	Fill missing Quantity with the mode quantity for that product

In [ ]:
s=a['Quantity'].mode()[0]
s

np.float64(-2.0)

In [ ]:
a['Quantity'].fillna(a['Quantity'].mode()[0],inplace=True)
a

/tmp/ipykernel_2327/4252636878.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  a['Quantity'].fillna(a['Quantity'].mode()[0],inplace=True)

,Order_ID,Customer_ID,Product_ID,Product_Name,Order_Amount,Payment_Mode,Order_Date,Shipping_Address,Quantity,Email,...,Discount,Delivery_Time,Status,Shipping_Fee,Tracking_Number,Billing_Address,Delivery_Date,Price,Category,temp_notes
0,101126,1179,102,Camera,7.322619e+04,ccard,2023-10-12,Delhi,5.0,fmflokr@gmail.com,...,20,5,Pending,150,NaN,Bengaluru,13-08-2020,30950.579179,Fashion,temp
1,100252,1088,58,Headphones,-5.000000e+01,COD,2020-02-09,unspecified,4.0,NaN,...,50,1,Cancelled,50,TRK4890,Chennai,2024/01/24,47454.499755,Fashion,temp
2,100776,1089,62,Mobile,0.000000e+00,ccard,2020-02-15,Delhi,4.0,oyjbadm@hotmail.com,...,50,2,Pending,150,TRK8989,Delhi,2024/09/15,22597.755842,Fashion,temp
3,100995,1013,104,Camera,0.000000e+00,UPI,2024-01-06,Hyderabad,4.0,itngklv@gmail.com,...,5,-3,delivred,150,TRK9684,Chennai,25-08-2023,3912.622055,Accessories,note1
4,101367,1128,145,Camera,8.156460e+04,Debit Card,2024-05-25,Hyderabad,3.0,srkahlm@yahoo.com,...,50,1,delivred,100,NaN,Delhi,2024/09/20,16394.129437,Accessories,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4951,100818,1176,151,Watch,2.000000e+06,Credit Card,2022-10-20,Mumbai,-2.0,mvxanjp@gmail.com,...,20,5,Delivered,-20,TRK9669,Mumbai,07-07-2019,28892.278292,Accessories,note1
4952,101609,1018,77,Shoes,-5.000000e+01,upiid,2020-12-01,Bengaluru,5.0,xfryyqf@gmal.com,...,5,-3,delivred,50,NaN,Mumbai,2021/02/16,16199.058547,Electronics,-
4982,101160,1139,67,Laptop,2.000000e+06,ccard,2021-10-12,Delhi,2.0,umxsowu@yahoo.com,...,20,-3,pendng,50,NaN,Bengaluru,05-05-2023,25562.242481,Fashion,temp
4984,100832,1064,151,Mobile,8.000390e+04,ccard,2021-09-25,Chennai,5.0,hzggukg@gmal.com,...,5,3,delivred,50,TRK1565,Chennai,23/12/21,29784.570278,Accessories,-
4987,101129,1164,17,Laptop,0.000000e+00,upiid,2019-12-09,Hyderabad,1.0,djpflcp@gmail.com,...,50,1,Delivered,-20,NaN,Bengaluru,2020/06/14,206.415472,Accessories,-

10.	Replace missing Email with "noemail@ecom.com".

In [ ]:
a['Email']=a['Email'].fillna('noemail@ecom.com')
a

,Order_ID,Customer_ID,Product_ID,Product_Name,Order_Amount,Payment_Mode,Order_Date,Shipping_Address,Quantity,Email,...,Discount,Delivery_Time,Status,Shipping_Fee,Tracking_Number,Billing_Address,Delivery_Date,Price,Category,temp_notes
0,101126,1179,102,Camera,7.322619e+04,ccard,2023-10-12,Delhi,5.0,fmflokr@gmail.com,...,20,5,Pending,150,NaN,Bengaluru,13-08-2020,30950.579179,Fashion,temp
1,100252,1088,58,Headphones,-5.000000e+01,COD,2020-02-09,unspecified,4.0,noemail@ecom.com,...,50,1,Cancelled,50,TRK4890,Chennai,2024/01/24,47454.499755,Fashion,temp
2,100776,1089,62,Mobile,0.000000e+00,ccard,2020-02-15,Delhi,4.0,oyjbadm@hotmail.com,...,50,2,Pending,150,TRK8989,Delhi,2024/09/15,22597.755842,Fashion,temp
3,100995,1013,104,Camera,0.000000e+00,UPI,2024-01-06,Hyderabad,4.0,itngklv@gmail.com,...,5,-3,delivred,150,TRK9684,Chennai,25-08-2023,3912.622055,Accessories,note1
4,101367,1128,145,Camera,8.156460e+04,Debit Card,2024-05-25,Hyderabad,3.0,srkahlm@yahoo.com,...,50,1,delivred,100,NaN,Delhi,2024/09/20,16394.129437,Accessories,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4951,100818,1176,151,Watch,2.000000e+06,Credit Card,2022-10-20,Mumbai,-2.0,mvxanjp@gmail.com,...,20,5,Delivered,-20,TRK9669,Mumbai,07-07-2019,28892.278292,Accessories,note1
4952,101609,1018,77,Shoes,-5.000000e+01,upiid,2020-12-01,Bengaluru,5.0,xfryyqf@gmal.com,...,5,-3,delivred,50,NaN,Mumbai,2021/02/16,16199.058547,Electronics,-
4982,101160,1139,67,Laptop,2.000000e+06,ccard,2021-10-12,Delhi,2.0,umxsowu@yahoo.com,...,20,-3,pendng,50,NaN,Bengaluru,05-05-2023,25562.242481,Fashion,temp
4984,100832,1064,151,Mobile,8.000390e+04,ccard,2021-09-25,Chennai,5.0,hzggukg@gmal.com,...,5,3,delivred,50,TRK1565,Chennai,23/12/21,29784.570278,Accessories,-
4987,101129,1164,17,Laptop,0.000000e+00,upiid,2019-12-09,Hyderabad,1.0,djpflcp@gmail.com,...,50,1,Delivered,-20,NaN,Bengaluru,2020/06/14,206.415472,Accessories,-

B. Invalid / Outlier Values

1.	Remove rows where Order_Amount <= 0

In [ ]:
for i in a.index :
  if a.loc[i,'Order_Amount']<=0 :
    a.drop(i,inplace=True)

In [ ]:
a

,Order_ID,Customer_ID,Product_ID,Product_Name,Order_Amount,Payment_Mode,Order_Date,Shipping_Address,Quantity,Email,...,Discount,Delivery_Time,Status,Shipping_Fee,Tracking_Number,Billing_Address,Delivery_Date,Price,Category,temp_notes
0,101126,1179,102,Camera,7.322619e+04,ccard,2023-10-12,Delhi,5.0,fmflokr@gmail.com,...,20,5,Pending,150,NaN,Bengaluru,13-08-2020,30950.579179,Fashion,temp
4,101367,1128,145,Camera,8.156460e+04,Debit Card,2024-05-25,Hyderabad,3.0,srkahlm@yahoo.com,...,50,1,delivred,100,NaN,Delhi,2024/09/20,16394.129437,Accessories,NaN
5,101895,1034,110,Camera,7.135315e+04,Credit Card,2019-05-18,unspecified,5.0,mgwyhez@hotmail.com,...,10,-3,pendng,-20,TRK1863,Chennai,18-07-2019,25526.820420,Fashion,note1
6,101430,1142,180,Watch,2.000000e+06,Debit Card,2022-12-25,Mumbai,-2.0,wjewgkt@hotmail.com,...,120,-3,delivred,150,NaN,Mumbai,05/06/23,16352.382046,Accessories,NaN
7,101496,1189,138,Laptop,6.480424e+04,creadit card,2022-04-11,unspecified,4.0,wyzpguy@gmail.com,...,5,3,Pending,150,TRK1663,Delhi,20-06-2022,20311.041319,Fashion,note1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4905,100304,1091,99,Laptop,2.000000e+06,upiid,2021-10-18,Mumbai,2.0,nrfnrfg@hotmail.com,...,20,3,pendng,150,NaN,Mumbai,08/07/23,27592.992544,Electronics,note1
4913,101640,1026,55,Mobile,2.000000e+06,Debit Card,2023-05-17,Hyderabad,-2.0,jotmtnw@hotmail.com,...,50,2,pendng,150,NaN,Bengaluru,22-09-2022,39769.981534,Accessories,temp
4951,100818,1176,151,Watch,2.000000e+06,Credit Card,2022-10-20,Mumbai,-2.0,mvxanjp@gmail.com,...,20,5,Delivered,-20,TRK9669,Mumbai,07-07-2019,28892.278292,Accessories,note1
4982,101160,1139,67,Laptop,2.000000e+06,ccard,2021-10-12,Delhi,2.0,umxsowu@yahoo.com,...,20,-3,pendng,50,NaN,Bengaluru,05-05-2023,25562.242481,Fashion,temp
4984,100832,1064,151,Mobile,8.000390e+04,ccard,2021-09-25,Chennai,5.0,hzggukg@gmal.com,...,5,3,delivred,50,TRK1565,Chennai,23/12/21,29784.570278,Accessories,-

2.	Remove rows with negative Quantity

In [ ]:
for i in a.index :
  if a.loc[i,'Quantity']<0 :
    a.drop(i,inplace=True)

In [ ]:
a

,Order_ID,Customer_ID,Product_ID,Product_Name,Order_Amount,Payment_Mode,Order_Date,Shipping_Address,Quantity,Email,...,Discount,Delivery_Time,Status,Shipping_Fee,Tracking_Number,Billing_Address,Delivery_Date,Price,Category,temp_notes
0,101126,1179,102,Camera,7.322619e+04,ccard,2023-10-12,Delhi,5.0,fmflokr@gmail.com,...,20,5,Pending,150,NaN,Bengaluru,13-08-2020,30950.579179,Fashion,temp
4,101367,1128,145,Camera,8.156460e+04,Debit Card,2024-05-25,Hyderabad,3.0,srkahlm@yahoo.com,...,50,1,delivred,100,NaN,Delhi,2024/09/20,16394.129437,Accessories,NaN
5,101895,1034,110,Camera,7.135315e+04,Credit Card,2019-05-18,unspecified,5.0,mgwyhez@hotmail.com,...,10,-3,pendng,-20,TRK1863,Chennai,18-07-2019,25526.820420,Fashion,note1
7,101496,1189,138,Laptop,6.480424e+04,creadit card,2022-04-11,unspecified,4.0,wyzpguy@gmail.com,...,5,3,Pending,150,TRK1663,Delhi,20-06-2022,20311.041319,Fashion,note1
10,100488,1160,177,Camera,9.367933e+04,COD,2023-05-24,unspecified,3.0,ekxnpek@gmail.com,...,5,-3,delivred,50,TRK3049,Bengaluru,20-04-2024,45040.819247,Accessories,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4857,100575,1004,179,Mobile,2.000000e+06,creadit card,2020-08-13,Bengaluru,5.0,kcnkctv@hotmail.com,...,95,1,pendng,-20,TRK4843,Chennai,08-12-2023,37538.792046,Electronics,NaN
4874,100053,1039,187,Laptop,2.380147e+04,ccard,NaT,Bengaluru,5.0,bdwuiis@gmail.com,...,5,5,Cancelled,100,NaN,Chennai,17/03/19,9214.851110,Electronics,NaN
4905,100304,1091,99,Laptop,2.000000e+06,upiid,2021-10-18,Mumbai,2.0,nrfnrfg@hotmail.com,...,20,3,pendng,150,NaN,Mumbai,08/07/23,27592.992544,Electronics,note1
4982,101160,1139,67,Laptop,2.000000e+06,ccard,2021-10-12,Delhi,2.0,umxsowu@yahoo.com,...,20,-3,pendng,50,NaN,Bengaluru,05-05-2023,25562.242481,Fashion,temp
4984,100832,1064,151,Mobile,8.000390e+04,ccard,2021-09-25,Chennai,5.0,hzggukg@gmal.com,...,5,3,delivred,50,TRK1565,Chennai,23/12/21,29784.570278,Accessories,-

4.	Fix mixed Order_Date formats (dd-mm-yyyy, yyyy/mm/dd)

In [ ]:
a['Order_Date'] = pd.to_datetime(a['Order_Date'],format='mixed')
a['Order_Date'] = a['Order_Date'].dt.strftime('%Y-%m-%d')
a

,Order_ID,Customer_ID,Product_ID,Product_Name,Order_Amount,Payment_Mode,Order_Date,Shipping_Address,Quantity,Email,...,Discount,Delivery_Time,Status,Shipping_Fee,Tracking_Number,Billing_Address,Delivery_Date,Price,Category,temp_notes
0,101126,1179,102,Camera,7.322619e+04,ccard,2023-10-12,Delhi,5.0,fmflokr@gmail.com,...,20,5,Pending,150,NaN,Bengaluru,13-08-2020,30950.579179,Fashion,temp
4,101367,1128,145,Camera,8.156460e+04,Debit Card,2024-05-25,Hyderabad,3.0,srkahlm@yahoo.com,...,50,1,delivred,100,NaN,Delhi,2024/09/20,16394.129437,Accessories,NaN
5,101895,1034,110,Camera,7.135315e+04,Credit Card,2019-05-18,unspecified,5.0,mgwyhez@hotmail.com,...,10,-3,pendng,-20,TRK1863,Chennai,18-07-2019,25526.820420,Fashion,note1
7,101496,1189,138,Laptop,6.480424e+04,creadit card,2022-04-11,unspecified,4.0,wyzpguy@gmail.com,...,5,3,Pending,150,TRK1663,Delhi,20-06-2022,20311.041319,Fashion,note1
10,100488,1160,177,Camera,9.367933e+04,COD,2023-05-24,unspecified,3.0,ekxnpek@gmail.com,...,5,-3,delivred,50,TRK3049,Bengaluru,20-04-2024,45040.819247,Accessories,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4857,100575,1004,179,Mobile,2.000000e+06,creadit card,2020-08-13,Bengaluru,5.0,kcnkctv@hotmail.com,...,95,1,pendng,-20,TRK4843,Chennai,08-12-2023,37538.792046,Electronics,NaN
4874,100053,1039,187,Laptop,2.380147e+04,ccard,NaN,Bengaluru,5.0,bdwuiis@gmail.com,...,5,5,Cancelled,100,NaN,Chennai,17/03/19,9214.851110,Electronics,NaN
4905,100304,1091,99,Laptop,2.000000e+06,upiid,2021-10-18,Mumbai,2.0,nrfnrfg@hotmail.com,...,20,3,pendng,150,NaN,Mumbai,08/07/23,27592.992544,Electronics,note1
4982,101160,1139,67,Laptop,2.000000e+06,ccard,2021-10-12,Delhi,2.0,umxsowu@yahoo.com,...,20,-3,pendng,50,NaN,Bengaluru,05-05-2023,25562.242481,Fashion,temp
4984,100832,1064,151,Mobile,8.000390e+04,ccard,2021-09-25,Chennai,5.0,hzggukg@gmal.com,...,5,3,delivred,50,TRK1565,Chennai,23/12/21,29784.570278,Accessories,-

5.	Correct typos in Payment_Mode (credit card, upi id).

In [ ]:
a['Payment_Mode'].unique()

array(['ccard', 'Debit Card', 'Credit Card', 'creadit card', 'COD',
       'upiid', 'UPI', 'cashh'], dtype=object)

In [ ]:
a['Payment_Mode']=a['Payment_Mode'].replace({'ccard':'Credit Card','creadit card':'Credit Card','upiid':'UPI','cashh':'Cash'})
a

,Order_ID,Customer_ID,Product_ID,Product_Name,Order_Amount,Payment_Mode,Order_Date,Shipping_Address,Quantity,Email,...,Discount,Delivery_Time,Status,Shipping_Fee,Tracking_Number,Billing_Address,Delivery_Date,Price,Category,temp_notes
0,101126,1179,102,Camera,7.322619e+04,Credit Card,2023-10-12,Delhi,5.0,fmflokr@gmail.com,...,20,5,Pending,150,NaN,Bengaluru,13-08-2020,30950.579179,Fashion,temp
4,101367,1128,145,Camera,8.156460e+04,Debit Card,2024-05-25,Hyderabad,3.0,srkahlm@yahoo.com,...,50,1,delivred,100,NaN,Delhi,2024/09/20,16394.129437,Accessories,NaN
5,101895,1034,110,Camera,7.135315e+04,Credit Card,2019-05-18,unspecified,5.0,mgwyhez@hotmail.com,...,10,-3,pendng,-20,TRK1863,Chennai,18-07-2019,25526.820420,Fashion,note1
7,101496,1189,138,Laptop,6.480424e+04,Credit Card,2022-04-11,unspecified,4.0,wyzpguy@gmail.com,...,5,3,Pending,150,TRK1663,Delhi,20-06-2022,20311.041319,Fashion,note1
10,100488,1160,177,Camera,9.367933e+04,COD,2023-05-24,unspecified,3.0,ekxnpek@gmail.com,...,5,-3,delivred,50,TRK3049,Bengaluru,20-04-2024,45040.819247,Accessories,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4857,100575,1004,179,Mobile,2.000000e+06,Credit Card,2020-08-13,Bengaluru,5.0,kcnkctv@hotmail.com,...,95,1,pendng,-20,TRK4843,Chennai,08-12-2023,37538.792046,Electronics,NaN
4874,100053,1039,187,Laptop,2.380147e+04,Credit Card,NaN,Bengaluru,5.0,bdwuiis@gmail.com,...,5,5,Cancelled,100,NaN,Chennai,17/03/19,9214.851110,Electronics,NaN
4905,100304,1091,99,Laptop,2.000000e+06,UPI,2021-10-18,Mumbai,2.0,nrfnrfg@hotmail.com,...,20,3,pendng,150,NaN,Mumbai,08/07/23,27592.992544,Electronics,note1
4982,101160,1139,67,Laptop,2.000000e+06,Credit Card,2021-10-12,Delhi,2.0,umxsowu@yahoo.com,...,20,-3,pendng,50,NaN,Bengaluru,05-05-2023,25562.242481,Fashion,temp
4984,100832,1064,151,Mobile,8.000390e+04,Credit Card,2021-09-25,Chennai,5.0,hzggukg@gmal.com,...,5,3,delivred,50,TRK1565,Chennai,23/12/21,29784.570278,Accessories,-

6.	Fix country/city typos

In [ ]:
a['Country'].unique()

array(['USAA', 'USA', 'India', 'Indai', 'UK'], dtype=object)

In [ ]:
a['Country']=a['Country'].replace({'USAA':'USA','Indai':'India'})
a

,Order_ID,Customer_ID,Product_ID,Product_Name,Order_Amount,Payment_Mode,Order_Date,Shipping_Address,Quantity,Email,...,Discount,Delivery_Time,Status,Shipping_Fee,Tracking_Number,Billing_Address,Delivery_Date,Price,Category,temp_notes
0,101126,1179,102,Camera,7.322619e+04,Credit Card,2023-10-12,Delhi,5.0,fmflokr@gmail.com,...,20,5,Pending,150,NaN,Bengaluru,13-08-2020,30950.579179,Fashion,temp
4,101367,1128,145,Camera,8.156460e+04,Debit Card,2024-05-25,Hyderabad,3.0,srkahlm@yahoo.com,...,50,1,delivred,100,NaN,Delhi,2024/09/20,16394.129437,Accessories,NaN
5,101895,1034,110,Camera,7.135315e+04,Credit Card,2019-05-18,unspecified,5.0,mgwyhez@hotmail.com,...,10,-3,pendng,-20,TRK1863,Chennai,18-07-2019,25526.820420,Fashion,note1
7,101496,1189,138,Laptop,6.480424e+04,Credit Card,2022-04-11,unspecified,4.0,wyzpguy@gmail.com,...,5,3,Pending,150,TRK1663,Delhi,20-06-2022,20311.041319,Fashion,note1
10,100488,1160,177,Camera,9.367933e+04,COD,2023-05-24,unspecified,3.0,ekxnpek@gmail.com,...,5,-3,delivred,50,TRK3049,Bengaluru,20-04-2024,45040.819247,Accessories,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4857,100575,1004,179,Mobile,2.000000e+06,Credit Card,2020-08-13,Bengaluru,5.0,kcnkctv@hotmail.com,...,95,1,pendng,-20,TRK4843,Chennai,08-12-2023,37538.792046,Electronics,NaN
4874,100053,1039,187,Laptop,2.380147e+04,Credit Card,NaN,Bengaluru,5.0,bdwuiis@gmail.com,...,5,5,Cancelled,100,NaN,Chennai,17/03/19,9214.851110,Electronics,NaN
4905,100304,1091,99,Laptop,2.000000e+06,UPI,2021-10-18,Mumbai,2.0,nrfnrfg@hotmail.com,...,20,3,pendng,150,NaN,Mumbai,08/07/23,27592.992544,Electronics,note1
4982,101160,1139,67,Laptop,2.000000e+06,Credit Card,2021-10-12,Delhi,2.0,umxsowu@yahoo.com,...,20,-3,pendng,50,NaN,Bengaluru,05-05-2023,25562.242481,Fashion,temp
4984,100832,1064,151,Mobile,8.000390e+04,Credit Card,2021-09-25,Chennai,5.0,hzggukg@gmal.com,...,5,3,delivred,50,TRK1565,Chennai,23/12/21,29784.570278,Accessories,-

In [ ]:
a['Country'].head(20)

0       USA
4       USA
5     India
7     India
10    India
13    India
20       UK
22    India
23    India
24    India
26    India
28       UK
33      USA
34    India
35      USA
39    India
40      USA
42      USA
43      USA
44      USA
Name: Country, dtype: object

6.	Fix country/city typos

In [ ]:
a['City'].unique()

array(['Delhii', 'Chennai', 'chennai ', 'Delhi', 'Mumba1'], dtype=object)

In [ ]:
a['City']=a['City'].replace({'Delhii':'Delhi','chennai':'Chennai','Mumba1':'Mumbai'})
a

,Order_ID,Customer_ID,Product_ID,Product_Name,Order_Amount,Payment_Mode,Order_Date,Shipping_Address,Quantity,Email,...,Discount,Delivery_Time,Status,Shipping_Fee,Tracking_Number,Billing_Address,Delivery_Date,Price,Category,temp_notes
0,101126,1179,102,Camera,7.322619e+04,Credit Card,2023-10-12,Delhi,5.0,fmflokr@gmail.com,...,20,5,Pending,150,NaN,Bengaluru,13-08-2020,30950.579179,Fashion,temp
4,101367,1128,145,Camera,8.156460e+04,Debit Card,2024-05-25,Hyderabad,3.0,srkahlm@yahoo.com,...,50,1,delivred,100,NaN,Delhi,2024/09/20,16394.129437,Accessories,NaN
5,101895,1034,110,Camera,7.135315e+04,Credit Card,2019-05-18,unspecified,5.0,mgwyhez@hotmail.com,...,10,-3,pendng,-20,TRK1863,Chennai,18-07-2019,25526.820420,Fashion,note1
7,101496,1189,138,Laptop,6.480424e+04,Credit Card,2022-04-11,unspecified,4.0,wyzpguy@gmail.com,...,5,3,Pending,150,TRK1663,Delhi,20-06-2022,20311.041319,Fashion,note1
10,100488,1160,177,Camera,9.367933e+04,COD,2023-05-24,unspecified,3.0,ekxnpek@gmail.com,...,5,-3,delivred,50,TRK3049,Bengaluru,20-04-2024,45040.819247,Accessories,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4857,100575,1004,179,Mobile,2.000000e+06,Credit Card,2020-08-13,Bengaluru,5.0,kcnkctv@hotmail.com,...,95,1,pendng,-20,TRK4843,Chennai,08-12-2023,37538.792046,Electronics,NaN
4874,100053,1039,187,Laptop,2.380147e+04,Credit Card,NaN,Bengaluru,5.0,bdwuiis@gmail.com,...,5,5,Cancelled,100,NaN,Chennai,17/03/19,9214.851110,Electronics,NaN
4905,100304,1091,99,Laptop,2.000000e+06,UPI,2021-10-18,Mumbai,2.0,nrfnrfg@hotmail.com,...,20,3,pendng,150,NaN,Mumbai,08/07/23,27592.992544,Electronics,note1
4982,101160,1139,67,Laptop,2.000000e+06,Credit Card,2021-10-12,Delhi,2.0,umxsowu@yahoo.com,...,20,-3,pendng,50,NaN,Bengaluru,05-05-2023,25562.242481,Fashion,temp
4984,100832,1064,151,Mobile,8.000390e+04,Credit Card,2021-09-25,Chennai,5.0,hzggukg@gmal.com,...,5,3,delivred,50,TRK1565,Chennai,23/12/21,29784.570278,Accessories,-

In [ ]:
a['City'].head(20)

0        Delhi
4      Chennai
5     chennai
7        Delhi
10    chennai
13       Delhi
20       Delhi
22     Chennai
23       Delhi
24    chennai
26       Delhi
28       Delhi
33     Chennai
34    chennai
35       Delhi
39      Mumbai
40       Delhi
42    chennai
43      Mumbai
44     Chennai
Name: City, dtype: object

7.	Replace unrealistic Discount (> 90%) with median discount.

In [ ]:
s=a['Discount'].median()
s

50.0

In [ ]:
from numpy import median
for i in a.index :
  if a.loc[i,'Discount'] >90 :
    a.loc[i,'Discount'] = s

In [ ]:
a

,Order_ID,Customer_ID,Product_ID,Product_Name,Order_Amount,Payment_Mode,Order_Date,Shipping_Address,Quantity,Email,...,Discount,Delivery_Time,Status,Shipping_Fee,Tracking_Number,Billing_Address,Delivery_Date,Price,Category,temp_notes
0,101126,1179,102,Camera,7.322619e+04,Credit Card,2023-10-12,Delhi,5.0,fmflokr@gmail.com,...,20,5,Pending,150,NaN,Bengaluru,13-08-2020,30950.579179,Fashion,temp
4,101367,1128,145,Camera,8.156460e+04,Debit Card,2024-05-25,Hyderabad,3.0,srkahlm@yahoo.com,...,50,1,delivred,100,NaN,Delhi,2024/09/20,16394.129437,Accessories,NaN
5,101895,1034,110,Camera,7.135315e+04,Credit Card,2019-05-18,unspecified,5.0,mgwyhez@hotmail.com,...,10,-3,pendng,-20,TRK1863,Chennai,18-07-2019,25526.820420,Fashion,note1
7,101496,1189,138,Laptop,6.480424e+04,Credit Card,2022-04-11,unspecified,4.0,wyzpguy@gmail.com,...,5,3,Pending,150,TRK1663,Delhi,20-06-2022,20311.041319,Fashion,note1
10,100488,1160,177,Camera,9.367933e+04,COD,2023-05-24,unspecified,3.0,ekxnpek@gmail.com,...,5,-3,delivred,50,TRK3049,Bengaluru,20-04-2024,45040.819247,Accessories,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4857,100575,1004,179,Mobile,2.000000e+06,Credit Card,2020-08-13,Bengaluru,5.0,kcnkctv@hotmail.com,...,50,1,pendng,-20,TRK4843,Chennai,08-12-2023,37538.792046,Electronics,NaN
4874,100053,1039,187,Laptop,2.380147e+04,Credit Card,NaN,Bengaluru,5.0,bdwuiis@gmail.com,...,5,5,Cancelled,100,NaN,Chennai,17/03/19,9214.851110,Electronics,NaN
4905,100304,1091,99,Laptop,2.000000e+06,UPI,2021-10-18,Mumbai,2.0,nrfnrfg@hotmail.com,...,20,3,pendng,150,NaN,Mumbai,08/07/23,27592.992544,Electronics,note1
4982,101160,1139,67,Laptop,2.000000e+06,Credit Card,2021-10-12,Delhi,2.0,umxsowu@yahoo.com,...,20,-3,pendng,50,NaN,Bengaluru,05-05-2023,25562.242481,Fashion,temp
4984,100832,1064,151,Mobile,8.000390e+04,Credit Card,2021-09-25,Chennai,5.0,hzggukg@gmal.com,...,5,3,delivred,50,TRK1565,Chennai,23/12/21,29784.570278,Accessories,-

8.	Remove rows where Delivery_Time < 0.

In [ ]:
for i in a.index :
  if a.loc[i,'Delivery_Time'] <0 :
    a.drop(i,inplace=True)

In [ ]:
a

,Order_ID,Customer_ID,Product_ID,Product_Name,Order_Amount,Payment_Mode,Order_Date,Shipping_Address,Quantity,Email,...,Discount,Delivery_Time,Status,Shipping_Fee,Tracking_Number,Billing_Address,Delivery_Date,Price,Category,temp_notes
0,101126,1179,102,Camera,7.322619e+04,Credit Card,2023-10-12,Delhi,5.0,fmflokr@gmail.com,...,20,5,Pending,150,NaN,Bengaluru,13-08-2020,30950.579179,Fashion,temp
4,101367,1128,145,Camera,8.156460e+04,Debit Card,2024-05-25,Hyderabad,3.0,srkahlm@yahoo.com,...,50,1,delivred,100,NaN,Delhi,2024/09/20,16394.129437,Accessories,NaN
7,101496,1189,138,Laptop,6.480424e+04,Credit Card,2022-04-11,unspecified,4.0,wyzpguy@gmail.com,...,5,3,Pending,150,TRK1663,Delhi,20-06-2022,20311.041319,Fashion,note1
13,100658,1003,44,Laptop,2.000000e+06,UPI,2020-05-12,unspecified,4.0,hdhzitl@gmail.com,...,50,1,pendng,-20,NaN,Chennai,13/02/21,15423.711561,Accessories,note1
20,100496,1127,169,Headphones,2.000000e+06,Debit Card,2024-08-24,Chennai,2.0,biokraq@gmail.com,...,50,3,Delivered,50,TRK4913,Bengaluru,12-10-2018,10886.538161,Fashion,temp
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4855,101534,1153,13,Headphones,7.668544e+02,Cash,NaN,Mumbai,4.0,ysqrxbq@yahoo.com,...,50,1,delivred,100,TRK2416,Bengaluru,2022/01/03,43434.001308,Accessories,NaN
4857,100575,1004,179,Mobile,2.000000e+06,Credit Card,2020-08-13,Bengaluru,5.0,kcnkctv@hotmail.com,...,50,1,pendng,-20,TRK4843,Chennai,08-12-2023,37538.792046,Electronics,NaN
4874,100053,1039,187,Laptop,2.380147e+04,Credit Card,NaN,Bengaluru,5.0,bdwuiis@gmail.com,...,5,5,Cancelled,100,NaN,Chennai,17/03/19,9214.851110,Electronics,NaN
4905,100304,1091,99,Laptop,2.000000e+06,UPI,2021-10-18,Mumbai,2.0,nrfnrfg@hotmail.com,...,20,3,pendng,150,NaN,Mumbai,08/07/23,27592.992544,Electronics,note1
4984,100832,1064,151,Mobile,8.000390e+04,Credit Card,2021-09-25,Chennai,5.0,hzggukg@gmal.com,...,5,3,delivred,50,TRK1565,Chennai,23/12/21,29784.570278,Accessories,-

9.	Standardize Status values (Delivered, Pending, Cancelled).

In [ ]:
a['Status'].unique()

array(['Pending', 'delivred', 'pendng', 'Delivered', 'Cancelled'],
      dtype=object)

In [ ]:
a['Status']=a['Status'].replace({'pendng':'Pending','delivred':'Delivered'})
a

,Order_ID,Customer_ID,Product_ID,Product_Name,Order_Amount,Payment_Mode,Order_Date,Shipping_Address,Quantity,Email,...,Discount,Delivery_Time,Status,Shipping_Fee,Tracking_Number,Billing_Address,Delivery_Date,Price,Category,temp_notes
0,101126,1179,102,Camera,7.322619e+04,Credit Card,2023-10-12,Delhi,5.0,fmflokr@gmail.com,...,20,5,Pending,150,NaN,Bengaluru,13-08-2020,30950.579179,Fashion,temp
4,101367,1128,145,Camera,8.156460e+04,Debit Card,2024-05-25,Hyderabad,3.0,srkahlm@yahoo.com,...,50,1,Delivered,100,NaN,Delhi,2024/09/20,16394.129437,Accessories,NaN
7,101496,1189,138,Laptop,6.480424e+04,Credit Card,2022-04-11,unspecified,4.0,wyzpguy@gmail.com,...,5,3,Pending,150,TRK1663,Delhi,20-06-2022,20311.041319,Fashion,note1
13,100658,1003,44,Laptop,2.000000e+06,UPI,2020-05-12,unspecified,4.0,hdhzitl@gmail.com,...,50,1,Pending,-20,NaN,Chennai,13/02/21,15423.711561,Accessories,note1
20,100496,1127,169,Headphones,2.000000e+06,Debit Card,2024-08-24,Chennai,2.0,biokraq@gmail.com,...,50,3,Delivered,50,TRK4913,Bengaluru,12-10-2018,10886.538161,Fashion,temp
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4855,101534,1153,13,Headphones,7.668544e+02,Cash,NaN,Mumbai,4.0,ysqrxbq@yahoo.com,...,50,1,Delivered,100,TRK2416,Bengaluru,2022/01/03,43434.001308,Accessories,NaN
4857,100575,1004,179,Mobile,2.000000e+06,Credit Card,2020-08-13,Bengaluru,5.0,kcnkctv@hotmail.com,...,50,1,Pending,-20,TRK4843,Chennai,08-12-2023,37538.792046,Electronics,NaN
4874,100053,1039,187,Laptop,2.380147e+04,Credit Card,NaN,Bengaluru,5.0,bdwuiis@gmail.com,...,5,5,Cancelled,100,NaN,Chennai,17/03/19,9214.851110,Electronics,NaN
4905,100304,1091,99,Laptop,2.000000e+06,UPI,2021-10-18,Mumbai,2.0,nrfnrfg@hotmail.com,...,20,3,Pending,150,NaN,Mumbai,08/07/23,27592.992544,Electronics,note1
4984,100832,1064,151,Mobile,8.000390e+04,Credit Card,2021-09-25,Chennai,5.0,hzggukg@gmal.com,...,5,3,Delivered,50,TRK1565,Chennai,23/12/21,29784.570278,Accessories,-

10.	Fix negative Shipping_Fee values

In [ ]:
v=a['Shipping_Fee'].median()
v

100.0

In [ ]:
for i in a.index :
  if a.loc[i,'Shipping_Fee'] <0 :
    a.loc[i,'Shipping_Fee'] = v

In [ ]:
a

,Order_ID,Customer_ID,Product_ID,Product_Name,Order_Amount,Payment_Mode,Order_Date,Shipping_Address,Quantity,Email,...,Discount,Delivery_Time,Status,Shipping_Fee,Tracking_Number,Billing_Address,Delivery_Date,Price,Category,temp_notes
0,101126,1179,102,Camera,7.322619e+04,Credit Card,2023-10-12,Delhi,5.0,fmflokr@gmail.com,...,20,5,Pending,150,NaN,Bengaluru,13-08-2020,30950.579179,Fashion,temp
4,101367,1128,145,Camera,8.156460e+04,Debit Card,2024-05-25,Hyderabad,3.0,srkahlm@yahoo.com,...,50,1,Delivered,100,NaN,Delhi,2024/09/20,16394.129437,Accessories,NaN
7,101496,1189,138,Laptop,6.480424e+04,Credit Card,2022-04-11,unspecified,4.0,wyzpguy@gmail.com,...,5,3,Pending,150,TRK1663,Delhi,20-06-2022,20311.041319,Fashion,note1
13,100658,1003,44,Laptop,2.000000e+06,UPI,2020-05-12,unspecified,4.0,hdhzitl@gmail.com,...,50,1,Pending,100,NaN,Chennai,13/02/21,15423.711561,Accessories,note1
20,100496,1127,169,Headphones,2.000000e+06,Debit Card,2024-08-24,Chennai,2.0,biokraq@gmail.com,...,50,3,Delivered,50,TRK4913,Bengaluru,12-10-2018,10886.538161,Fashion,temp
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4855,101534,1153,13,Headphones,7.668544e+02,Cash,NaN,Mumbai,4.0,ysqrxbq@yahoo.com,...,50,1,Delivered,100,TRK2416,Bengaluru,2022/01/03,43434.001308,Accessories,NaN
4857,100575,1004,179,Mobile,2.000000e+06,Credit Card,2020-08-13,Bengaluru,5.0,kcnkctv@hotmail.com,...,50,1,Pending,100,TRK4843,Chennai,08-12-2023,37538.792046,Electronics,NaN
4874,100053,1039,187,Laptop,2.380147e+04,Credit Card,NaN,Bengaluru,5.0,bdwuiis@gmail.com,...,5,5,Cancelled,100,NaN,Chennai,17/03/19,9214.851110,Electronics,NaN
4905,100304,1091,99,Laptop,2.000000e+06,UPI,2021-10-18,Mumbai,2.0,nrfnrfg@hotmail.com,...,20,3,Pending,150,NaN,Mumbai,08/07/23,27592.992544,Electronics,note1
4984,100832,1064,151,Mobile,8.000390e+04,Credit Card,2021-09-25,Chennai,5.0,hzggukg@gmal.com,...,5,3,Delivered,50,TRK1565,Chennai,23/12/21,29784.570278,Accessories,-

C. Conditional Fetch / Filtering

1.	Fetch orders with Order_Amount > 50,000

In [ ]:
for i in a.index :
  if a.loc[i,'Order_Amount'] > 50000 :
    print(a.loc[i][['Order_ID','Order_Amount']])

Order_ID              101126
Order_Amount    73226.194787
Name: 0, dtype: object
Order_ID              101367
Order_Amount    81564.596703
Name: 4, dtype: object
Order_ID              101496
Order_Amount    64804.243042
Name: 7, dtype: object
Order_ID           100658
Order_Amount    2000000.0
Name: 13, dtype: object
Order_ID           100496
Order_Amount    2000000.0
Name: 20, dtype: object
Order_ID           101819
Order_Amount    2000000.0
Name: 23, dtype: object
Order_ID           101866
Order_Amount    2000000.0
Name: 24, dtype: object
Order_ID           100958
Order_Amount    2000000.0
Name: 28, dtype: object
Order_ID              101887
Order_Amount    97313.723892
Name: 33, dtype: object
Order_ID           100046
Order_Amount    2000000.0
Name: 34, dtype: object
Order_ID           100362
Order_Amount    2000000.0
Name: 35, dtype: object
Order_ID              100009
Order_Amount    98997.027216
Name: 39, dtype: object
Order_ID              101692
Order_Amount    99769.492331
Name: 42, dtype: object
Order_ID           100957
Order_Amount    2000000.0
Name: 44, dtype: object
Order_ID           100147
Order_Amount    2000000.0
Name: 47, dtype: object
Order_ID           101529
Order_Amount    2000000.0
Name: 51, dtype: object
Order_ID              101750
Order_Amount    91438.450775
Name: 52, dtype: object
Order_ID           101185
Order_Amount    2000000.0
Name: 69, dtype: object
Order_ID              100606
Order_Amount    69528.690424
Name: 71, dtype: object
Order_ID           100493
Order_Amount    2000000.0
Name: 86, dtype: object
Order_ID           100035
Order_Amount    2000000.0
Name: 87, dtype: object
Order_ID              100489
Order_Amount    54019.288614
Name: 94, dtype: object
Order_ID           100553
Order_Amount    2000000.0
Name: 100, dtype: object
Order_ID           100199
Order_Amount    2000000.0
Name: 101, dtype: object
Order_ID           101325
Order_Amount    2000000.0
Name: 111, dtype: object
Order_ID           101542
Order_Amount    2000000.0
Name: 113, dtype: object
Order_ID           101600
Order_Amount    2000000.0
Name: 115, dtype: object
Order_ID           101091
Order_Amount    2000000.0
Name: 116, dtype: object
Order_ID              100929
Order_Amount    73176.499385
Name: 120, dtype: object
Order_ID              100654
Order_Amount    66890.407408
Name: 132, dtype: object
Order_ID           101373
Order_Amount    2000000.0
Name: 133, dtype: object
Order_ID           101219
Order_Amount    2000000.0
Name: 135, dtype: object
Order_ID              101457
Order_Amount    53238.079382
Name: 136, dtype: object
Order_ID             101110
Order_Amount    54583.57401
Name: 137, dtype: object
Order_ID              100164
Order_Amount    85270.522412
Name: 139, dtype: object
Order_ID           100902
Order_Amount    2000000.0
Name: 141, dtype: object
Order_ID           101589
Order_Amount    2000000.0
Name: 142, dtype: object
Order_ID           100271
Order_Amount    2000000.0
Name: 157, dtype: object
Order_ID              101913
Order_Amount    86690.358415
Name: 161, dtype: object
Order_ID           101619
Order_Amount    2000000.0
Name: 179, dtype: object
Order_ID              100415
Order_Amount    73158.520318
Name: 184, dtype: object
Order_ID           100313
Order_Amount    2000000.0
Name: 187, dtype: object
Order_ID              100597
Order_Amount    91668.669834
Name: 192, dtype: object
Order_ID           100941
Order_Amount    2000000.0
Name: 196, dtype: object
Order_ID           100903
Order_Amount    2000000.0
Name: 198, dtype: object
Order_ID           100830
Order_Amount    2000000.0
Name: 200, dtype: object
Order_ID           100855
Order_Amount    2000000.0
Name: 207, dtype: object
Order_ID           101602
Order_Amount    2000000.0
Name: 209, dtype: object
Order_ID              100128
Order_Amount    94028.058477
Name: 210, dtype: object
Order_ID           100452
Order_Amount    2000000.0
Name: 218, dtype: object
Order_ID           101816
Order_Amount    2000000.0
Name: 228, dtype: object
Order_ID           101498
Order_Amount    2000000.0
Name: 234, dtype: object
Order_ID           101464
Order_Amount    2000000.0
Name: 239, dtype: object
Order_ID           101658
Order_Amount    2000000.0
Name: 240, dtype: object
Order_ID              100556
Order_Amount    99458.740705
Name: 245, dtype: object
Order_ID           101001
Order_Amount    2000000.0
Name: 254, dtype: object
Order_ID           101104
Order_Amount    2000000.0
Name: 270, dtype: object
Order_ID           100089
Order_Amount    2000000.0
Name: 287, dtype: object
Order_ID           101419
Order_Amount    2000000.0
Name: 291, dtype: object
Order_ID              100727
Order_Amount    98738.110384
Name: 307, dtype: object
Order_ID              100162
Order_Amount    52866.107249
Name: 310, dtype: object
Order_ID            100811
Order_Amount    98850.1994
Name: 325, dtype: object
Order_ID           101632
Order_Amount    2000000.0
Name: 329, dtype: object
Order_ID           101022
Order_Amount    2000000.0
Name: 332, dtype: object
Order_ID              100772
Order_Amount    60817.066017
Name: 337, dtype: object
Order_ID           101933
Order_Amount    2000000.0
Name: 345, dtype: object
Order_ID              100845
Order_Amount    98658.292129
Name: 346, dtype: object
Order_ID              100232
Order_Amount    87161.705322
Name: 355, dtype: object
Order_ID           101500
Order_Amount    2000000.0
Name: 356, dtype: object
Order_ID           101394
Order_Amount    2000000.0
Name: 358, dtype: object
Order_ID           100700
Order_Amount    2000000.0
Name: 362, dtype: object
Order_ID           101176
Order_Amount    2000000.0
Name: 367, dtype: object
Order_ID              101315
Order_Amount    92986.193091
Name: 372, dtype: object
Order_ID           101557
Order_Amount    2000000.0
Name: 376, dtype: object
Order_ID              100544
Order_Amount    86198.197947
Name: 378, dtype: object
Order_ID           101777
Order_Amount    2000000.0
Name: 383, dtype: object
Order_ID           100105
Order_Amount    2000000.0
Name: 389, dtype: object
Order_ID              101440
Order_Amount    50456.600967
Name: 409, dtype: object
Order_ID           101389
Order_Amount    2000000.0
Name: 410, dtype: object
Order_ID           100702
Order_Amount    2000000.0
Name: 421, dtype: object
Order_ID           101060
Order_Amount    2000000.0
Name: 425, dtype: object
Order_ID           101301
Order_Amount    2000000.0
Name: 426, dtype: object
Order_ID              101488
Order_Amount    66971.603825
Name: 430, dtype: object
Order_ID              100887
Order_Amount    74956.603979
Name: 431, dtype: object
Order_ID              101170
Order_Amount    93605.818482
Name: 432, dtype: object
Order_ID           100178
Order_Amount    2000000.0
Name: 435, dtype: object
Order_ID           100591
Order_Amount    2000000.0
Name: 436, dtype: object
Order_ID           101699
Order_Amount    2000000.0
Name: 441, dtype: object
Order_ID           101738
Order_Amount    2000000.0
Name: 464, dtype: object
Order_ID           101548
Order_Amount    2000000.0
Name: 465, dtype: object
Order_ID              101477
Order_Amount    81288.035033
Name: 469, dtype: object
Order_ID           100279
Order_Amount    2000000.0
Name: 471, dtype: object
Order_ID           100906
Order_Amount    2000000.0
Name: 490, dtype: object
Order_ID             100617
Order_Amount    66851.24813
Name: 493, dtype: object
Order_ID              100249
Order_Amount    66186.279982
Name: 503, dtype: object
Order_ID           100821
Order_Amount    2000000.0
Name: 510, dtype: object
Order_ID              101485
Order_Amount    96005.186894
Name: 514, dtype: object
Order_ID           100895
Order_Amount    2000000.0
Name: 517, dtype: object
Order_ID              100426
Order_Amount    88432.314448
Name: 524, dtype: object
Order_ID           100696
Order_Amount    2000000.0
Name: 529, dtype: object
Order_ID           101575
Order_Amount    2000000.0
Name: 538, dtype: object
Order_ID           101138
Order_Amount    2000000.0
Name: 540, dtype: object
Order_ID           100377
Order_Amount    2000000.0
Name: 546, dtype: object
Order_ID             100635
Order_Amount    90608.31615
Name: 549, dtype: object
Order_ID           100062
Order_Amount    2000000.0
Name: 550, dtype: object
Order_ID           100611
Order_Amount    2000000.0
Name: 552, dtype: object
Order_ID           100823
Order_Amount    2000000.0
Name: 568, dtype: object
Order_ID           100465
Order_Amount    2000000.0
Name: 584, dtype: object
Order_ID           100198
Order_Amount    2000000.0
Name: 599, dtype: object
Order_ID           101370
Order_Amount    2000000.0
Name: 600, dtype: object
Order_ID              100168
Order_Amount    55820.699434
Name: 603, dtype: object
Order_ID              101553
Order_Amount    91031.147971
Name: 610, dtype: object
Order_ID           101473
Order_Amount    2000000.0
Name: 615, dtype: object
Order_ID              101443
Order_Amount    87881.888624
Name: 616, dtype: object
Order_ID           101568
Order_Amount    2000000.0
Name: 620, dtype: object
Order_ID           101178
Order_Amount    2000000.0
Name: 636, dtype: object
Order_ID           100864
Order_Amount    2000000.0
Name: 641, dtype: object
Order_ID           101278
Order_Amount    2000000.0
Name: 656, dtype: object
Order_ID           101490
Order_Amount    2000000.0
Name: 660, dtype: object
Order_ID           100572
Order_Amount    2000000.0
Name: 672, dtype: object
Order_ID           101470
Order_Amount    2000000.0
Name: 674, dtype: object
Order_ID              100243
Order_Amount    82362.735738
Name: 680, dtype: object
Order_ID              101466
Order_Amount    50422.901256
Name: 705, dtype: object
Order_ID           100624
Order_Amount    2000000.0
Name: 709, dtype: object
Order_ID           100050
Order_Amount    2000000.0
Name: 717, dtype: object
Order_ID           100475
Order_Amount    2000000.0
Name: 722, dtype: object
Order_ID           101715
Order_Amount    2000000.0
Name: 728, dtype: object
Order_ID           101054
Order_Amount    2000000.0
Name: 730, dtype: object
Order_ID           100976
Order_Amount    2000000.0
Name: 733, dtype: object
Order_ID           101427
Order_Amount    2000000.0
Name: 749, dtype: object
Order_ID              101872
Order_Amount    88519.078668
Name: 763, dtype: object
Order_ID           101504
Order_Amount    2000000.0
Name: 771, dtype: object
Order_ID           100212
Order_Amount    2000000.0
Name: 777, dtype: object
Order_ID           101220
Order_Amount    2000000.0
Name: 782, dtype: object
Order_ID           101499
Order_Amount    2000000.0
Name: 791, dtype: object
Order_ID              100630
Order_Amount    77798.049598
Name: 795, dtype: object
Order_ID              100222
Order_Amount    95102.745621
Name: 806, dtype: object
Order_ID           101034
Order_Amount    2000000.0
Name: 814, dtype: object
Order_ID           100673
Order_Amount    2000000.0
Name: 825, dtype: object
Order_ID           100807
Order_Amount    2000000.0
Name: 827, dtype: object
Order_ID              101205
Order_Amount    68376.929068
Name: 833, dtype: object
Order_ID           100638
Order_Amount    2000000.0
Name: 835, dtype: object
Order_ID           101711
Order_Amount    2000000.0
Name: 836, dtype: object
Order_ID           101294
Order_Amount    2000000.0
Name: 838, dtype: object
Order_ID              100639
Order_Amount    74814.436177
Name: 864, dtype: object
Order_ID           100165
Order_Amount    2000000.0
Name: 870, dtype: object
Order_ID           100809
Order_Amount    2000000.0
Name: 877, dtype: object
Order_ID              101121
Order_Amount    93368.290271
Name: 895, dtype: object
Order_ID              101838
Order_Amount    60870.705066
Name: 897, dtype: object
Order_ID           101690
Order_Amount    2000000.0
Name: 906, dtype: object
Order_ID           100200
Order_Amount    2000000.0
Name: 907, dtype: object
Order_ID           100586
Order_Amount    2000000.0
Name: 913, dtype: object
Order_ID           100709
Order_Amount    2000000.0
Name: 930, dtype: object
Order_ID           100429
Order_Amount    2000000.0
Name: 936, dtype: object
Order_ID           100459
Order_Amount    2000000.0
Name: 937, dtype: object
Order_ID           100648
Order_Amount    2000000.0
Name: 943, dtype: object
Order_ID           101970
Order_Amount    2000000.0
Name: 946, dtype: object
Order_ID           101423
Order_Amount    2000000.0
Name: 954, dtype: object
Order_ID           101799
Order_Amount    2000000.0
Name: 956, dtype: object
Order_ID              101011
Order_Amount    61579.027175
Name: 957, dtype: object
Order_ID           101044
Order_Amount    2000000.0
Name: 961, dtype: object
Order_ID              101637
Order_Amount    81997.335103
Name: 981, dtype: object
Order_ID           100359
Order_Amount    2000000.0
Name: 990, dtype: object
Order_ID              101019
Order_Amount    99224.742404
Name: 995, dtype: object
Order_ID              101016
Order_Amount    54618.559606
Name: 1000, dtype: object
Order_ID           101768
Order_Amount    2000000.0
Name: 1013, dtype: object
Order_ID           100290
Order_Amount    2000000.0
Name: 1020, dtype: object
Order_ID              101652
Order_Amount    74456.066071
Name: 1027, dtype: object
Order_ID           101783
Order_Amount    2000000.0
Name: 1041, dtype: object
Order_ID           101865
Order_Amount    2000000.0
Name: 1044, dtype: object
Order_ID           100237
Order_Amount    2000000.0
Name: 1061, dtype: object
Order_ID           101410
Order_Amount    2000000.0
Name: 1072, dtype: object
Order_ID              101415
Order_Amount    81921.298882
Name: 1087, dtype: object
Order_ID           101474
Order_Amount    2000000.0
Name: 1088, dtype: object
Order_ID              101615
Order_Amount    84497.123652
Name: 1103, dtype: object
Order_ID           101482
Order_Amount    2000000.0
Name: 1124, dtype: object
Order_ID           101679
Order_Amount    2000000.0
Name: 1126, dtype: object
Order_ID           101701
Order_Amount    2000000.0
Name: 1127, dtype: object
Order_ID              100539
Order_Amount    69878.232892
Name: 1135, dtype: object
Order_ID           100063
Order_Amount    2000000.0
Name: 1146, dtype: object
Order_ID           101569
Order_Amount    2000000.0
Name: 1148, dtype: object
Order_ID              101896
Order_Amount    66365.452583
Name: 1160, dtype: object
Order_ID              101710
Order_Amount    62553.664956
Name: 1168, dtype: object
Order_ID           100670
Order_Amount    2000000.0
Name: 1195, dtype: object
Order_ID           100340
Order_Amount    2000000.0
Name: 1206, dtype: object
Order_ID              101776
Order_Amount    57676.666997
Name: 1219, dtype: object
Order_ID              101928
Order_Amount    55957.913057
Name: 1240, dtype: object
Order_ID           100671
Order_Amount    2000000.0
Name: 1244, dtype: object
Order_ID              101753
Order_Amount    95454.153243
Name: 1278, dtype: object
Order_ID           100172
Order_Amount    2000000.0
Name: 1279, dtype: object
Order_ID              100118
Order_Amount    66447.961348
Name: 1281, dtype: object
Order_ID           101099
Order_Amount    2000000.0
Name: 1285, dtype: object
Order_ID           100064
Order_Amount    2000000.0
Name: 1293, dtype: object
Order_ID           101266
Order_Amount    2000000.0
Name: 1302, dtype: object
Order_ID           101274
Order_Amount    2000000.0
Name: 1313, dtype: object
Order_ID              100547
Order_Amount    75363.203859
Name: 1327, dtype: object
Order_ID           100230
Order_Amount    2000000.0
Name: 1338, dtype: object
Order_ID              100788
Order_Amount    96256.617788
Name: 1348, dtype: object
Order_ID           101202
Order_Amount    2000000.0
Name: 1353, dtype: object
Order_ID           101250
Order_Amount    2000000.0
Name: 1359, dtype: object
Order_ID           101065
Order_Amount    2000000.0
Name: 1363, dtype: object
Order_ID              100564
Order_Amount    72397.270107
Name: 1368, dtype: object
Order_ID           100481
Order_Amount    2000000.0
Name: 1376, dtype: object
Order_ID              101617
Order_Amount    91877.223576
Name: 1382, dtype: object
Order_ID           101746
Order_Amount    2000000.0
Name: 1409, dtype: object
Order_ID              100480
Order_Amount    95706.458819
Name: 1412, dtype: object
Order_ID           101503
Order_Amount    2000000.0
Name: 1418, dtype: object
Order_ID           100924
Order_Amount    2000000.0
Name: 1420, dtype: object
Order_ID           101953
Order_Amount    2000000.0
Name: 1430, dtype: object
Order_ID           101239
Order_Amount    2000000.0
Name: 1444, dtype: object
Order_ID           100754
Order_Amount    2000000.0
Name: 1461, dtype: object
Order_ID           100231
Order_Amount    2000000.0
Name: 1537, dtype: object
Order_ID           101582
Order_Amount    2000000.0
Name: 1584, dtype: object
Order_ID           100103
Order_Amount    2000000.0
Name: 1596, dtype: object
Order_ID           101078
Order_Amount    2000000.0
Name: 1599, dtype: object
Order_ID           101369
Order_Amount    2000000.0
Name: 1623, dtype: object
Order_ID           101986
Order_Amount    2000000.0
Name: 1637, dtype: object
Order_ID           101661
Order_Amount    2000000.0
Name: 1643, dtype: object
Order_ID           100017
Order_Amount    2000000.0
Name: 1656, dtype: object
Order_ID              100413
Order_Amount    85011.291541
Name: 1659, dtype: object
Order_ID              101074
Order_Amount    64498.722166
Name: 1665, dtype: object
Order_ID           101177
Order_Amount    2000000.0
Name: 1668, dtype: object
Order_ID              101790
Order_Amount    54528.558292
Name: 1673, dtype: object
Order_ID           100774
Order_Amount    2000000.0
Name: 1680, dtype: object
Order_ID           100295
Order_Amount    2000000.0
Name: 1693, dtype: object
Order_ID              100614
Order_Amount    76145.297646
Name: 1721, dtype: object
Order_ID              100746
Order_Amount    68331.075249
Name: 1724, dtype: object
Order_ID           101108
Order_Amount    2000000.0
Name: 1725, dtype: object
Order_ID              100476
Order_Amount    74171.800937
Name: 1727, dtype: object
Order_ID           101077
Order_Amount    2000000.0
Name: 1733, dtype: object
Order_ID           100778
Order_Amount    2000000.0
Name: 1756, dtype: object
Order_ID           101420
Order_Amount    2000000.0
Name: 1757, dtype: object
Order_ID           101779
Order_Amount    2000000.0
Name: 1759, dtype: object
Order_ID           101341
Order_Amount    2000000.0
Name: 1774, dtype: object
Order_ID           101724
Order_Amount    2000000.0
Name: 1802, dtype: object
Order_ID           101449
Order_Amount    2000000.0
Name: 1812, dtype: object
Order_ID           100579
Order_Amount    2000000.0
Name: 1846, dtype: object
Order_ID           101850
Order_Amount    2000000.0
Name: 1882, dtype: object
Order_ID           100286
Order_Amount    2000000.0
Name: 1883, dtype: object
Order_ID           100901
Order_Amount    2000000.0
Name: 1906, dtype: object
Order_ID           100996
Order_Amount    2000000.0
Name: 1936, dtype: object
Order_ID           101644
Order_Amount    2000000.0
Name: 1952, dtype: object
Order_ID           100603
Order_Amount    2000000.0
Name: 1962, dtype: object
Order_ID           100777
Order_Amount    2000000.0
Name: 1966, dtype: object
Order_ID              100567
Order_Amount    57700.578714
Name: 1967, dtype: object
Order_ID              100113
Order_Amount    84157.927125
Name: 1969, dtype: object
Order_ID              101795
Order_Amount    79878.054938
Name: 1976, dtype: object
Order_ID              100436
Order_Amount    67868.821235
Name: 1982, dtype: object
Order_ID           101006
Order_Amount    2000000.0
Name: 1984, dtype: object
Order_ID           100092
Order_Amount    2000000.0
Name: 1988, dtype: object
Order_ID           100416
Order_Amount    2000000.0
Name: 2007, dtype: object
Order_ID           101815
Order_Amount    2000000.0
Name: 2022, dtype: object
Order_ID              101386
Order_Amount    70024.195336

2.	Fetch orders with Quantity > 10

In [ ]:
a['Quantity'].value_counts()

Quantity
4.0    111
2.0    109
1.0     96
5.0     90
3.0     85
Name: count, dtype: int64

3.	Fetch orders with Payment_Mode = UPI

In [ ]:
for i in a.index :
  if a.loc[i,'Payment_Mode']=='UPI' :
    print(a.loc[i][['Product_Name','Order_Amount','Payment_Mode']])

Product_Name       Laptop
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 13, dtype: object
Product_Name     Backpack
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 34, dtype: object
Product_Name       Backpack
Order_Amount    4904.654932
Payment_Mode            UPI
Name: 40, dtype: object
Product_Name       Laptop
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 51, dtype: object
Product_Name          Shoes
Order_Amount    18031.78261
Payment_Mode            UPI
Name: 66, dtype: object
Product_Name           Watch
Order_Amount    38422.864815
Payment_Mode             UPI
Name: 67, dtype: object
Product_Name      Headphones
Order_Amount    69528.690424
Payment_Mode             UPI
Name: 71, dtype: object
Product_Name          Mobile
Order_Amount    54019.288614
Payment_Mode             UPI
Name: 94, dtype: object
Product_Name           Shoes
Order_Amount    85270.522412
Payment_Mode             UPI
Name: 139, dtype: object
Product_Name       Camera
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 141, dtype: object
Product_Name     Backpack
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 142, dtype: object
Product_Name        Shoes
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 234, dtype: object
Product_Name       Mobile
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 239, dtype: object
Product_Name           Watch
Order_Amount    99458.740705
Payment_Mode             UPI
Name: 245, dtype: object
Product_Name      Headphones
Order_Amount    25072.291798
Payment_Mode             UPI
Name: 263, dtype: object
Product_Name     Backpack
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 270, dtype: object
Product_Name           Shoes
Order_Amount    21432.931164
Payment_Mode             UPI
Name: 305, dtype: object
Product_Name          Laptop
Order_Amount    18368.166223
Payment_Mode             UPI
Name: 306, dtype: object
Product_Name           Shoes
Order_Amount    87161.705322
Payment_Mode             UPI
Name: 355, dtype: object
Product_Name       Camera
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 358, dtype: object
Product_Name        Shoes
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 362, dtype: object
Product_Name     Backpack
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 367, dtype: object
Product_Name      Headphones
Order_Amount    86198.197947
Payment_Mode             UPI
Name: 378, dtype: object
Product_Name       Mobile
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 383, dtype: object
Product_Name        Shoes
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 389, dtype: object
Product_Name           Shoes
Order_Amount    10440.943406
Payment_Mode             UPI
Name: 405, dtype: object
Product_Name        Watch
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 436, dtype: object
Product_Name       Camera
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 510, dtype: object
Product_Name          Laptop
Order_Amount    96005.186894
Payment_Mode             UPI
Name: 514, dtype: object
Product_Name        Watch
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 529, dtype: object
Product_Name       Mobile
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 538, dtype: object
Product_Name       Camera
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 568, dtype: object
Product_Name          Mobile
Order_Amount    55820.699434
Payment_Mode             UPI
Name: 603, dtype: object
Product_Name           Watch
Order_Amount    87881.888624
Payment_Mode             UPI
Name: 616, dtype: object
Product_Name          Camera
Order_Amount    18045.419255
Payment_Mode             UPI
Name: 626, dtype: object
Product_Name       Camera
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 674, dtype: object
Product_Name          Shoes
Order_Amount    8327.063735
Payment_Mode            UPI
Name: 686, dtype: object
Product_Name           Watch
Order_Amount    39721.219054
Payment_Mode             UPI
Name: 694, dtype: object
Product_Name    Headphones
Order_Amount     2000000.0
Payment_Mode           UPI
Name: 717, dtype: object
Product_Name       Camera
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 722, dtype: object
Product_Name          Camera
Order_Amount    88519.078668
Payment_Mode             UPI
Name: 763, dtype: object
Product_Name     Backpack
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 835, dtype: object
Product_Name       Camera
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 838, dtype: object
Product_Name           Watch
Order_Amount    45808.786197
Payment_Mode             UPI
Name: 866, dtype: object
Product_Name       Camera
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 877, dtype: object
Product_Name           Watch
Order_Amount    25020.181569
Payment_Mode             UPI
Name: 903, dtype: object
Product_Name        Watch
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 906, dtype: object
Product_Name        Shoes
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 954, dtype: object
Product_Name     Backpack
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 961, dtype: object
Product_Name           Shoes
Order_Amount    99224.742404
Payment_Mode             UPI
Name: 995, dtype: object
Product_Name           Watch
Order_Amount    54618.559606
Payment_Mode             UPI
Name: 1000, dtype: object
Product_Name        Shoes
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 1013, dtype: object
Product_Name          Laptop
Order_Amount    74456.066071
Payment_Mode             UPI
Name: 1027, dtype: object
Product_Name       Laptop
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 1061, dtype: object
Product_Name        Watch
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 1072, dtype: object
Product_Name          Mobile
Order_Amount    81921.298882
Payment_Mode             UPI
Name: 1087, dtype: object
Product_Name         Watch
Order_Amount    435.901594
Payment_Mode           UPI
Name: 1102, dtype: object
Product_Name     Backpack
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 1127, dtype: object
Product_Name      Headphones
Order_Amount    33688.974702
Payment_Mode             UPI
Name: 1193, dtype: object
Product_Name        Backpack
Order_Amount    39192.272941
Payment_Mode             UPI
Name: 1213, dtype: object
Product_Name        Backpack
Order_Amount    57676.666997
Payment_Mode             UPI
Name: 1219, dtype: object
Product_Name           Shoes
Order_Amount    95454.153243
Payment_Mode             UPI
Name: 1278, dtype: object
Product_Name          Mobile
Order_Amount    35324.607987
Payment_Mode             UPI
Name: 1301, dtype: object
Product_Name      Headphones
Order_Amount    31896.686796
Payment_Mode             UPI
Name: 1314, dtype: object
Product_Name       Laptop
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 1338, dtype: object
Product_Name           Shoes
Order_Amount    96256.617788
Payment_Mode             UPI
Name: 1348, dtype: object
Product_Name        Shoes
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 1376, dtype: object
Product_Name          Mobile
Order_Amount    42805.249101
Payment_Mode             UPI
Name: 1385, dtype: object
Product_Name       Mobile
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 1409, dtype: object
Product_Name           Watch
Order_Amount    95706.458819
Payment_Mode             UPI
Name: 1412, dtype: object
Product_Name    Headphones
Order_Amount     2000000.0
Payment_Mode           UPI
Name: 1420, dtype: object
Product_Name       Laptop
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 1537, dtype: object
Product_Name       Camera
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 1599, dtype: object
Product_Name         Mobile
Order_Amount    34641.84536
Payment_Mode            UPI
Name: 1625, dtype: object
Product_Name       Laptop
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 1668, dtype: object
Product_Name       Mobile
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 1725, dtype: object
Product_Name       Camera
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 1802, dtype: object
Product_Name      Headphones
Order_Amount    34952.153124
Payment_Mode             UPI
Name: 1886, dtype: object
Product_Name          Mobile
Order_Amount    35210.682936
Payment_Mode             UPI
Name: 1931, dtype: object
Product_Name       Laptop
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 1962, dtype: object
Product_Name       Mobile
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 1984, dtype: object
Product_Name    Headphones
Order_Amount     2000000.0
Payment_Mode           UPI
Name: 2022, dtype: object
Product_Name          Laptop
Order_Amount    70024.195336
Payment_Mode             UPI
Name: 2036, dtype: object
Product_Name    Headphones
Order_Amount     2000000.0
Payment_Mode           UPI
Name: 2095, dtype: object
Product_Name          Laptop
Order_Amount    23614.331138
Payment_Mode             UPI
Name: 2145, dtype: object
Product_Name    Headphones
Order_Amount     2000000.0
Payment_Mode           UPI
Name: 2189, dtype: object
Product_Name     Backpack
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 2195, dtype: object
Product_Name          Mobile
Order_Amount    15330.981193
Payment_Mode             UPI
Name: 2218, dtype: object
Product_Name           Watch
Order_Amount    62035.643726
Payment_Mode             UPI
Name: 2229, dtype: object
Product_Name    Headphones
Order_Amount     2000000.0
Payment_Mode           UPI
Name: 2257, dtype: object
Product_Name        Watch
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 2360, dtype: object
Product_Name         Watch
Order_Amount    2017.58675
Payment_Mode           UPI
Name: 2391, dtype: object
Product_Name          Camera
Order_Amount    63591.470737
Payment_Mode             UPI
Name: 2407, dtype: object
Product_Name          Laptop
Order_Amount    13884.518821
Payment_Mode             UPI
Name: 2544, dtype: object
Product_Name    Headphones
Order_Amount     2000000.0
Payment_Mode           UPI
Name: 2564, dtype: object
Product_Name        Shoes
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 2596, dtype: object
Product_Name       Mobile
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 2701, dtype: object
Product_Name       Camera
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 2719, dtype: object
Product_Name           Shoes
Order_Amount    53498.329094
Payment_Mode             UPI
Name: 3100, dtype: object
Product_Name         Mobile
Order_Amount    58445.61301
Payment_Mode            UPI
Name: 3113, dtype: object
Product_Name          Laptop
Order_Amount    35241.100941
Payment_Mode             UPI
Name: 3142, dtype: object
Product_Name        Shoes
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 3210, dtype: object
Product_Name       Camera
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 3369, dtype: object
Product_Name        Watch
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 3411, dtype: object
Product_Name       Mobile
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 3441, dtype: object
Product_Name       Mobile
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 3536, dtype: object
Product_Name       Laptop
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 3547, dtype: object
Product_Name           Shoes
Order_Amount    29578.120107
Payment_Mode             UPI
Name: 3647, dtype: object
Product_Name       Camera
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 3739, dtype: object
Product_Name         Mobile
Order_Amount    61735.79032
Payment_Mode            UPI
Name: 4061, dtype: object
Product_Name       Mobile
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 4073, dtype: object
Product_Name        Watch
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 4233, dtype: object
Product_Name        Backpack
Order_Amount    76337.370377
Payment_Mode             UPI
Name: 4630, dtype: object
Product_Name       Camera
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 4643, dtype: object
Product_Name       Camera
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 4658, dtype: object
Product_Name     Backpack
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 4784, dtype: object
Product_Name       Laptop
Order_Amount    2000000.0
Payment_Mode          UPI
Name: 4905, dtype: object

4.	Fetch orders where Delivery_Status = Pending

In [ ]:
for i in a.index :
  if a.loc[i,'Status']=='Pending' :
    print(a.loc[i][['Product_Name','Order_Amount','Status']])

Product_Name          Camera
Order_Amount    73226.194787
Status               Pending
Name: 0, dtype: object
Product_Name          Laptop
Order_Amount    64804.243042
Status               Pending
Name: 7, dtype: object
Product_Name       Laptop
Order_Amount    2000000.0
Status            Pending
Name: 13, dtype: object
Product_Name    Headphones
Order_Amount     2000000.0
Status             Pending
Name: 23, dtype: object
Product_Name       Laptop
Order_Amount    2000000.0
Status            Pending
Name: 24, dtype: object
Product_Name          Laptop
Order_Amount    37549.570894
Status               Pending
Name: 26, dtype: object
Product_Name        Watch
Order_Amount    2000000.0
Status            Pending
Name: 28, dtype: object
Product_Name     Backpack
Order_Amount    2000000.0
Status            Pending
Name: 34, dtype: object
Product_Name    Headphones
Order_Amount     2000000.0
Status             Pending
Name: 35, dtype: object
Product_Name           Shoes
Order_Amount    99769.492331
Status               Pending
Name: 42, dtype: object
Product_Name        Backpack
Order_Amount    91438.450775
Status               Pending
Name: 52, dtype: object
Product_Name          Shoes
Order_Amount    18031.78261
Status              Pending
Name: 66, dtype: object
Product_Name           Watch
Order_Amount    38422.864815
Status               Pending
Name: 67, dtype: object
Product_Name       Laptop
Order_Amount    2000000.0
Status            Pending
Name: 69, dtype: object
Product_Name       Camera
Order_Amount    2000000.0
Status            Pending
Name: 87, dtype: object
Product_Name          Mobile
Order_Amount    54019.288614
Status               Pending
Name: 94, dtype: object
Product_Name        Watch
Order_Amount    2000000.0
Status            Pending
Name: 100, dtype: object
Product_Name       Camera
Order_Amount    2000000.0
Status            Pending
Name: 113, dtype: object
Product_Name     Backpack
Order_Amount    2000000.0
Status            Pending
Name: 116, dtype: object
Product_Name        Backpack
Order_Amount    73176.499385
Status               Pending
Name: 120, dtype: object
Product_Name       Laptop
Order_Amount    2000000.0
Status            Pending
Name: 135, dtype: object
Product_Name       Camera
Order_Amount    2000000.0
Status            Pending
Name: 141, dtype: object
Product_Name        Shoes
Order_Amount    2000000.0
Status            Pending
Name: 157, dtype: object
Product_Name        Shoes
Order_Amount    2000000.0
Status            Pending
Name: 179, dtype: object
Product_Name        Watch
Order_Amount    2000000.0
Status            Pending
Name: 187, dtype: object
Product_Name        Backpack
Order_Amount    91668.669834
Status               Pending
Name: 192, dtype: object
Product_Name       Mobile
Order_Amount    2000000.0
Status            Pending
Name: 209, dtype: object
Product_Name        Backpack
Order_Amount    94028.058477
Status               Pending
Name: 210, dtype: object
Product_Name       Mobile
Order_Amount    2000000.0
Status            Pending
Name: 218, dtype: object
Product_Name           Shoes
Order_Amount    10648.595443
Status               Pending
Name: 225, dtype: object
Product_Name           Watch
Order_Amount    99458.740705
Status               Pending
Name: 245, dtype: object
Product_Name          Watch
Order_Amount    1992.645797
Status              Pending
Name: 255, dtype: object
Product_Name     Backpack
Order_Amount    2000000.0
Status            Pending
Name: 270, dtype: object
Product_Name        Backpack
Order_Amount    45811.775692
Status               Pending
Name: 284, dtype: object
Product_Name       Mobile
Order_Amount    2000000.0
Status            Pending
Name: 287, dtype: object
Product_Name          Camera
Order_Amount    98738.110384
Status               Pending
Name: 307, dtype: object
Product_Name          Mobile
Order_Amount    52866.107249
Status               Pending
Name: 310, dtype: object
Product_Name      Backpack
Order_Amount    98850.1994
Status             Pending
Name: 325, dtype: object
Product_Name       Laptop
Order_Amount    2000000.0
Status            Pending
Name: 356, dtype: object
Product_Name          Laptop
Order_Amount    44690.822485
Status               Pending
Name: 370, dtype: object
Product_Name          Mobile
Order_Amount    43858.377455
Status               Pending
Name: 373, dtype: object
Product_Name      Headphones
Order_Amount    86198.197947
Status               Pending
Name: 378, dtype: object
Product_Name       Mobile
Order_Amount    2000000.0
Status            Pending
Name: 383, dtype: object
Product_Name        Shoes
Order_Amount    2000000.0
Status            Pending
Name: 389, dtype: object
Product_Name           Shoes
Order_Amount    10440.943406
Status               Pending
Name: 405, dtype: object
Product_Name          Laptop
Order_Amount    50456.600967
Status               Pending
Name: 409, dtype: object
Product_Name     Backpack
Order_Amount    2000000.0
Status            Pending
Name: 421, dtype: object
Product_Name       Camera
Order_Amount    2000000.0
Status            Pending
Name: 425, dtype: object
Product_Name       Laptop
Order_Amount    2000000.0
Status            Pending
Name: 426, dtype: object
Product_Name           Watch
Order_Amount    66971.603825
Status               Pending
Name: 430, dtype: object
Product_Name          Mobile
Order_Amount    74956.603979
Status               Pending
Name: 431, dtype: object
Product_Name       Laptop
Order_Amount    2000000.0
Status            Pending
Name: 441, dtype: object
Product_Name       Mobile
Order_Amount    2000000.0
Status            Pending
Name: 465, dtype: object
Product_Name        Shoes
Order_Amount    2000000.0
Status            Pending
Name: 471, dtype: object
Product_Name    Headphones
Order_Amount     2000000.0
Status             Pending
Name: 517, dtype: object
Product_Name        Watch
Order_Amount    2000000.0
Status            Pending
Name: 529, dtype: object
Product_Name       Mobile
Order_Amount    2000000.0
Status            Pending
Name: 546, dtype: object
Product_Name     Backpack
Order_Amount    2000000.0
Status            Pending
Name: 550, dtype: object
Product_Name          Mobile
Order_Amount    55820.699434
Status               Pending
Name: 603, dtype: object
Product_Name       Mobile
Order_Amount    2000000.0
Status            Pending
Name: 620, dtype: object
Product_Name      Backpack
Order_Amount    44184.6515
Status             Pending
Name: 629, dtype: object
Product_Name     Backpack
Order_Amount    2000000.0
Status            Pending
Name: 656, dtype: object
Product_Name        Backpack
Order_Amount    82362.735738
Status               Pending
Name: 680, dtype: object
Product_Name           Watch
Order_Amount    39721.219054
Status               Pending
Name: 694, dtype: object
Product_Name           Watch
Order_Amount    39682.392434
Status               Pending
Name: 703, dtype: object
Product_Name    Headphones
Order_Amount     2000000.0
Status             Pending
Name: 717, dtype: object
Product_Name       Camera
Order_Amount    2000000.0
Status            Pending
Name: 722, dtype: object
Product_Name       Laptop
Order_Amount    2000000.0
Status            Pending
Name: 728, dtype: object
Product_Name    Headphones
Order_Amount     2000000.0
Status             Pending
Name: 730, dtype: object
Product_Name       Mobile
Order_Amount    2000000.0
Status            Pending
Name: 733, dtype: object
Product_Name       Mobile
Order_Amount    2000000.0
Status            Pending
Name: 749, dtype: object
Product_Name          Camera
Order_Amount    18785.564255
Status               Pending
Name: 759, dtype: object
Product_Name          Camera
Order_Amount    88519.078668
Status               Pending
Name: 763, dtype: object
Product_Name       Laptop
Order_Amount    2000000.0
Status            Pending
Name: 777, dtype: object
Product_Name        Watch
Order_Amount    2000000.0
Status            Pending
Name: 782, dtype: object
Product_Name        Laptop
Order_Amount    547.721163
Status             Pending
Name: 802, dtype: object
Product_Name        Watch
Order_Amount    2000000.0
Status            Pending
Name: 825, dtype: object
Product_Name     Backpack
Order_Amount    2000000.0
Status            Pending
Name: 835, dtype: object
Product_Name        Backpack
Order_Amount    74814.436177
Status               Pending
Name: 864, dtype: object
Product_Name           Watch
Order_Amount    45808.786197
Status               Pending
Name: 866, dtype: object
Product_Name       Camera
Order_Amount    2000000.0
Status            Pending
Name: 877, dtype: object
Product_Name          Mobile
Order_Amount    93368.290271
Status               Pending
Name: 895, dtype: object
Product_Name          Laptop
Order_Amount    60870.705066
Status               Pending
Name: 897, dtype: object
Product_Name           Watch
Order_Amount    25020.181569
Status               Pending
Name: 903, dtype: object
Product_Name    Headphones
Order_Amount     2000000.0
Status             Pending
Name: 930, dtype: object
Product_Name       Mobile
Order_Amount    2000000.0
Status            Pending
Name: 936, dtype: object
Product_Name          Mobile
Order_Amount    11203.667964
Status               Pending
Name: 939, dtype: object
Product_Name          Laptop
Order_Amount    11886.922112
Status               Pending
Name: 945, dtype: object
Product_Name        Shoes
Order_Amount    2000000.0
Status            Pending
Name: 954, dtype: object
Product_Name     Backpack
Order_Amount    2000000.0
Status            Pending
Name: 961, dtype: object
Product_Name     Headphones
Order_Amount    14589.82284
Status              Pending
Name: 971, dtype: object
Product_Name           Shoes
Order_Amount    15593.851266
Status               Pending
Name: 973, dtype: object
Product_Name        Backpack
Order_Amount    81997.335103
Status               Pending
Name: 981, dtype: object
Product_Name     Headphones
Order_Amount    2858.844121
Status              Pending
Name: 1035, dtype: object
Product_Name       Mobile
Order_Amount    2000000.0
Status            Pending
Name: 1044, dtype: object
Product_Name         Mobile
Order_Amount    5156.022992
Status              Pending
Name: 1050, dtype: object
Product_Name       Laptop
Order_Amount    2000000.0
Status            Pending
Name: 1061, dtype: object
Product_Name          Mobile
Order_Amount    81921.298882
Status               Pending
Name: 1087, dtype: object
Product_Name       Mobile
Order_Amount    2000000.0
Status            Pending
Name: 1088, dtype: object
Product_Name          Camera
Order_Amount    69878.232892
Status               Pending
Name: 1135, dtype: object
Product_Name       Camera
Order_Amount    2000000.0
Status            Pending
Name: 1279, dtype: object
Product_Name          Mobile
Order_Amount    35324.607987
Status               Pending
Name: 1301, dtype: object
Product_Name          Laptop
Order_Amount    17957.974497
Status               Pending
Name: 1304, dtype: object
Product_Name          Laptop
Order_Amount    91877.223576
Status               Pending
Name: 1382, dtype: object
Product_Name         Laptop
Order_Amount    5021.147398
Status              Pending
Name: 1383, dtype: object
Product_Name          Laptop
Order_Amount    26577.848518
Status               Pending
Name: 1387, dtype: object
Product_Name       Mobile
Order_Amount    2000000.0
Status            Pending
Name: 1409, dtype: object
Product_Name           Watch
Order_Amount    95706.458819
Status               Pending
Name: 1412, dtype: object
Product_Name    Headphones
Order_Amount     2000000.0
Status             Pending
Name: 1418, dtype: object
Product_Name       Laptop
Order_Amount    2000000.0
Status            Pending
Name: 1537, dtype: object
Product_Name           Watch
Order_Amount    17004.255956
Status               Pending
Name: 1562, dtype: object
Product_Name       Camera
Order_Amount    2000000.0
Status            Pending
Name: 1599, dtype: object
Product_Name          Shoes
Order_Amount    8168.541864
Status              Pending
Name: 1604, dtype: object
Product_Name     Backpack
Order_Amount    2000000.0
Status            Pending
Name: 1637, dtype: object
Product_Name        Backpack
Order_Amount    54528.558292
Status               Pending
Name: 1673, dtype: object
Product_Name        Backpack
Order_Amount    26140.772727
Status               Pending
Name: 1678, dtype: object
Product_Name       Mobile
Order_Amount    2000000.0
Status            Pending
Name: 1693, dtype: object
Product_Name           Shoes
Order_Amount    68331.075249
Status               Pending
Name: 1724, dtype: object
Product_Name          Camera
Order_Amount    74171.800937
Status               Pending
Name: 1727, dtype: object
Product_Name          Camera
Order_Amount    15258.143993
Status               Pending
Name: 1831, dtype: object
Product_Name       Mobile
Order_Amount    2000000.0
Status            Pending
Name: 1882, dtype: object
Product_Name      Headphones
Order_Amount    34952.153124
Status               Pending
Name: 1886, dtype: object
Product_Name         Mobile
Order_Amount    13220.38419
Status              Pending
Name: 1915, dtype: object
Product_Name         Mobile
Order_Amount    6118.025636
Status              Pending
Name: 1922, dtype: object
Product_Name       Laptop
Order_Amount    2000000.0
Status            Pending
Name: 1952, dtype: object
Product_Name          Camera
Order_Amount    84157.927125
Status               Pending
Name: 1969, dtype: object
Product_Name       Mobile
Order_Amount    2000000.0
Status            Pending
Name: 1984, dtype: object
Product_Name          Laptop
Order_Amount    70024.195336
Status               Pending
Name: 2036, dtype: object
Product_Name    Headphones
Order_Amount     2000000.0
Status             Pending
Name: 2068, dtype: object
Product_Name        Watch
Order_Amount    2000000.0
Status            Pending
Name: 2077, dtype: object
Product_Name    Headphones
Order_Amount     2000000.0
Status             Pending
Name: 2095, dtype: object
Product_Name          Laptop
Order_Amount    23614.331138
Status               Pending
Name: 2145, dtype: object
Product_Name          Laptop
Order_Amount    24203.911915
Status               Pending
Name: 2180, dtype: object
Product_Name    Headphones
Order_Amount     2000000.0
Status             Pending
Name: 2189, dtype: object
Product_Name          Camera
Order_Amount    59235.913228
Status               Pending
Name: 2211, dtype: object
Product_Name          Mobile
Order_Amount    15330.981193
Status               Pending
Name: 2218, dtype: object
Product_Name           Watch
Order_Amount    62035.643726
Status               Pending
Name: 2229, dtype: object
Product_Name    Headphones
Order_Amount     2000000.0
Status             Pending
Name: 2257, dtype: object
Product_Name     Backpack
Order_Amount    2000000.0
Status            Pending
Name: 2297, dtype: object
Product_Name    Headphones
Order_Amount     2000000.0
Status             Pending
Name: 2326, dtype: object
Product_Name        Watch
Order_Amount    2000000.0
Status            Pending
Name: 2337, dtype: object
Product_Name        Watch
Order_Amount    2000000.0
Status            Pending
Name: 2344, dtype: object
Product_Name           Watch
Order_Amount    21974.408277
Status               Pending
Name: 2345, dtype: object
Product_Name         Watch
Order_Amount    2017.58675
Status             Pending
Name: 2391, dtype: object
Product_Name          Camera
Order_Amount    63591.470737
Status               Pending
Name: 2407, dtype: object
Product_Name          Shoes
Order_Amount    45691.13663
Status              Pending
Name: 2476, dtype: object
Product_Name          Laptop
Order_Amount    13884.518821
Status               Pending
Name: 2544, dtype: object
Product_Name        Shoes
Order_Amount    2000000.0
Status            Pending
Name: 2689, dtype: object
Product_Name       Camera
Order_Amount    2000000.0
Status            Pending
Name: 2719, dtype: object
Product_Name        Watch
Order_Amount    2000000.0
Status            Pending
Name: 2774, dtype: object
Product_Name     Backpack
Order_Amount    2000000.0
Status            Pending
Name: 2794, dtype: object
Product_Name       Mobile
Order_Amount    2000000.0
Status            Pending
Name: 2803, dtype: object
Product_Name          Mobile
Order_Amount    41298.432514
Status               Pending
Name: 2985, dtype: object
Product_Name      Headphones
Order_Amount    41214.492775
Status               Pending
Name: 2993, dtype: object
Product_Name        Backpack
Order_Amount    89033.879583
Status               Pending
Name: 3018, dtype: object
Product_Name     Backpack
Order_Amount    2000000.0
Status            Pending
Name: 3087, dtype: object
Product_Name        Shoes
Order_Amount    2000000.0
Status            Pending
Name: 3090, dtype: object
Product_Name           Shoes
Order_Amount    53498.329094
Status               Pending
Name: 3100, dtype: object
Product_Name         Mobile
Order_Amount    58445.61301
Status              Pending
Name: 3113, dtype: object
Product_Name           Shoes
Order_Amount    11865.914149
Status               Pending
Name: 3118, dtype: object
Product_Name        Shoes
Order_Amount    2000000.0
Status            Pending
Name: 3145, dtype: object
Product_Name      Headphones
Order_Amount    40352.242152
Status               Pending
Name: 3158, dtype: object
Product_Name        Shoes
Order_Amount    2000000.0
Status            Pending
Name: 3210, dtype: object
Product_Name       Camera
Order_Amount    2000000.0
Status            Pending
Name: 3237, dtype: object
Product_Name           Watch
Order_Amount    44543.715407
Status               Pending
Name: 3257, dtype: object
Product_Name    Headphones
Order_Amount     2000000.0
Status             Pending
Name: 3301, dtype: object
Product_Name        Watch
Order_Amount    2000000.0
Status            Pending
Name: 3411, dtype: object
Product_Name      Headphones
Order_Amount    34424.751573
Status               Pending
Name: 3490, dtype: object
Product_Name        Backpack
Order_Amount    20281.827618
Status               Pending
Name: 3501, dtype: object
Product_Name        Watch
Order_Amount    2000000.0
Status            Pending
Name: 3513, dtype: object
Product_Name        Shoes
Order_Amount    2000000.0
Status            Pending
Name: 3531, dtype: object
Product_Name         Mobile
Order_Amount    4140.873644
Status              Pending
Name: 3541, dtype: object
Product_Name       Mobile
Order_Amount    2000000.0
Status            Pending
Name: 3557, dtype: object
Product_Name          Mobile
Order_Amount    14206.262706
Status               Pending
Name: 3608, dtype: object
Product_Name        Shoes
Order_Amount    2000000.0
Status            Pending
Name: 3622, dtype: object
Product_Name         Laptop
Order_Amount    22460.26338
Status              Pending
Name: 3655, dtype: object
Product_Name          Laptop
Order_Amount    69227.705188
Status               Pending
Name: 3698, dtype: object
Product_Name       Backpack
Order_Amount    3389.170125
Status              Pending
Name: 3709, dtype: object
Product_Name           Shoes
Order_Amount    90761.417951
Status               Pending
Name: 3733, dtype: object
Product_Name       Mobile
Order_Amount    2000000.0
Status            Pending
Name: 3766, dtype: object
Product_Name          Laptop
Order_Amount    11515.904543
Status               Pending
Name: 3795, dtype: object
Product_Name       Laptop
Order_Amount    2000000.0
Status            Pending
Name: 3806, dtype: object
Product_Name          Laptop
Order_Amount    18041.374647
Status               Pending
Name: 3814, dtype: object
Product_Name        Shoes
Order_Amount    2000000.0
Status            Pending
Name: 3820, dtype: object
Product_Name         Mobile
Order_Amount    61735.79032
Status              Pending
Name: 4061, dtype: object
Product_Name    Headphones
Order_Amount     2000000.0

5.	Fetch orders from Country = India.

In [ ]:
for i in a.index :
  if a.loc[i,'Country']=='India' :
    print(a.loc[i][['Product_Name','Order_Amount','Country']])

Product_Name          Laptop
Order_Amount    64804.243042
Country                India
Name: 7, dtype: object
Product_Name       Laptop
Order_Amount    2000000.0
Country             India
Name: 13, dtype: object
Product_Name    Headphones
Order_Amount     2000000.0
Country              India
Name: 23, dtype: object
Product_Name       Laptop
Order_Amount    2000000.0
Country             India
Name: 24, dtype: object
Product_Name          Laptop
Order_Amount    37549.570894
Country                India
Name: 26, dtype: object
Product_Name     Backpack
Order_Amount    2000000.0
Country             India
Name: 34, dtype: object
Product_Name          Mobile
Order_Amount    98997.027216
Country                India
Name: 39, dtype: object
Product_Name       Laptop
Order_Amount    2000000.0
Country             India
Name: 51, dtype: object
Product_Name        Backpack
Order_Amount    91438.450775
Country                India
Name: 52, dtype: object
Product_Name          Shoes
Order_Amount    18031.78261
Country               India
Name: 66, dtype: object
Product_Name       Laptop
Order_Amount    2000000.0
Country             India
Name: 69, dtype: object
Product_Name      Headphones
Order_Amount    69528.690424
Country                India
Name: 71, dtype: object
Product_Name       Camera
Order_Amount    2000000.0
Country             India
Name: 87, dtype: object
Product_Name          Mobile
Order_Amount    54019.288614
Country                India
Name: 94, dtype: object
Product_Name       Laptop
Order_Amount    2000000.0
Country             India
Name: 101, dtype: object
Product_Name        Watch
Order_Amount    2000000.0
Country             India
Name: 111, dtype: object
Product_Name       Camera
Order_Amount    2000000.0
Country             India
Name: 113, dtype: object
Product_Name        Watch
Order_Amount    2000000.0
Country             India
Name: 115, dtype: object
Product_Name        Backpack
Order_Amount    73176.499385
Country                India
Name: 120, dtype: object
Product_Name          Shoes
Order_Amount    54583.57401
Country               India
Name: 137, dtype: object
Product_Name        Shoes
Order_Amount    2000000.0
Country             India
Name: 157, dtype: object
Product_Name        Watch
Order_Amount    2000000.0
Country             India
Name: 187, dtype: object
Product_Name        Watch
Order_Amount    2000000.0
Country             India
Name: 196, dtype: object
Product_Name        Shoes
Order_Amount    2000000.0
Country             India
Name: 198, dtype: object
Product_Name       Laptop
Order_Amount    2000000.0
Country             India
Name: 200, dtype: object
Product_Name    Headphones
Order_Amount     2000000.0
Country              India
Name: 207, dtype: object
Product_Name       Mobile
Order_Amount    2000000.0
Country             India
Name: 209, dtype: object
Product_Name        Backpack
Order_Amount    94028.058477
Country                India
Name: 210, dtype: object
Product_Name        Shoes
Order_Amount    2000000.0
Country             India
Name: 234, dtype: object
Product_Name       Mobile
Order_Amount    2000000.0
Country             India
Name: 239, dtype: object
Product_Name           Watch
Order_Amount    99458.740705
Country                India
Name: 245, dtype: object
Product_Name       Laptop
Order_Amount    2000000.0
Country             India
Name: 254, dtype: object
Product_Name          Watch
Order_Amount    1992.645797
Country               India
Name: 255, dtype: object
Product_Name        Backpack
Order_Amount    45811.775692
Country                India
Name: 284, dtype: object
Product_Name       Mobile
Order_Amount    2000000.0
Country             India
Name: 287, dtype: object
Product_Name           Shoes
Order_Amount    21432.931164
Country                India
Name: 305, dtype: object
Product_Name       Camera
Order_Amount    2000000.0
Country             India
Name: 329, dtype: object
Product_Name          Laptop
Order_Amount    98658.292129
Country                India
Name: 346, dtype: object
Product_Name       Camera
Order_Amount    2000000.0
Country             India
Name: 358, dtype: object
Product_Name     Backpack
Order_Amount    2000000.0
Country             India
Name: 367, dtype: object
Product_Name          Laptop
Order_Amount    44690.822485
Country                India
Name: 370, dtype: object
Product_Name          Laptop
Order_Amount    92986.193091
Country                India
Name: 372, dtype: object
Product_Name       Mobile
Order_Amount    2000000.0
Country             India
Name: 383, dtype: object
Product_Name           Shoes
Order_Amount    39837.557818
Country                India
Name: 403, dtype: object
Product_Name          Laptop
Order_Amount    50456.600967
Country                India
Name: 409, dtype: object
Product_Name       Laptop
Order_Amount    2000000.0
Country             India
Name: 426, dtype: object
Product_Name     Headphones
Order_Amount    2486.030713
Country               India
Name: 429, dtype: object
Product_Name           Watch
Order_Amount    66971.603825
Country                India
Name: 430, dtype: object
Product_Name          Mobile
Order_Amount    74956.603979
Country                India
Name: 431, dtype: object
Product_Name       Laptop
Order_Amount    2000000.0
Country             India
Name: 435, dtype: object
Product_Name        Watch
Order_Amount    2000000.0
Country             India
Name: 436, dtype: object
Product_Name       Mobile
Order_Amount    2000000.0
Country             India
Name: 464, dtype: object
Product_Name       Mobile
Order_Amount    2000000.0
Country             India
Name: 465, dtype: object
Product_Name          Laptop
Order_Amount    81288.035033
Country                India
Name: 469, dtype: object
Product_Name       Mobile
Order_Amount    2000000.0
Country             India
Name: 490, dtype: object
Product_Name     Headphones
Order_Amount    66851.24813
Country               India
Name: 493, dtype: object
Product_Name          Laptop
Order_Amount    66186.279982
Country                India
Name: 503, dtype: object
Product_Name       Camera
Order_Amount    2000000.0
Country             India
Name: 510, dtype: object
Product_Name          Laptop
Order_Amount    96005.186894
Country                India
Name: 514, dtype: object
Product_Name           Watch
Order_Amount    88432.314448
Country                India
Name: 524, dtype: object
Product_Name        Watch
Order_Amount    2000000.0
Country             India
Name: 529, dtype: object
Product_Name     Backpack
Order_Amount    2000000.0
Country             India
Name: 550, dtype: object
Product_Name       Camera
Order_Amount    2000000.0
Country             India
Name: 552, dtype: object
Product_Name       Laptop
Order_Amount    2000000.0
Country             India
Name: 584, dtype: object
Product_Name       Camera
Order_Amount    2000000.0
Country             India
Name: 600, dtype: object
Product_Name     Backpack
Order_Amount    2000000.0
Country             India
Name: 615, dtype: object
Product_Name           Watch
Order_Amount    87881.888624
Country                India
Name: 616, dtype: object
Product_Name       Mobile
Order_Amount    2000000.0
Country             India
Name: 620, dtype: object
Product_Name          Camera
Order_Amount    18045.419255
Country                India
Name: 626, dtype: object
Product_Name        Shoes
Order_Amount    2000000.0
Country             India
Name: 636, dtype: object
Product_Name        Watch
Order_Amount    2000000.0
Country             India
Name: 641, dtype: object
Product_Name     Backpack
Order_Amount    2000000.0
Country             India
Name: 656, dtype: object
Product_Name     Backpack
Order_Amount    2000000.0
Country             India
Name: 660, dtype: object
Product_Name           Watch
Order_Amount    39682.392434
Country                India
Name: 703, dtype: object
Product_Name    Headphones
Order_Amount     2000000.0
Country              India
Name: 717, dtype: object
Product_Name       Mobile
Order_Amount    2000000.0
Country             India
Name: 733, dtype: object
Product_Name          Camera
Order_Amount    77798.049598
Country                India
Name: 795, dtype: object
Product_Name       Mobile
Order_Amount    2000000.0
Country             India
Name: 814, dtype: object
Product_Name        Watch
Order_Amount    2000000.0
Country             India
Name: 836, dtype: object
Product_Name          Mobile
Order_Amount    93368.290271
Country                India
Name: 895, dtype: object
Product_Name          Laptop
Order_Amount    60870.705066
Country                India
Name: 897, dtype: object
Product_Name           Watch
Order_Amount    25020.181569
Country                India
Name: 903, dtype: object
Product_Name        Watch
Order_Amount    2000000.0
Country             India
Name: 906, dtype: object
Product_Name       Mobile
Order_Amount    2000000.0
Country             India
Name: 936, dtype: object
Product_Name     Backpack
Order_Amount    2000000.0
Country             India
Name: 937, dtype: object
Product_Name        Shoes
Order_Amount    2000000.0
Country             India
Name: 954, dtype: object
Product_Name          Camera
Order_Amount    61579.027175
Country                India
Name: 957, dtype: object
Product_Name     Headphones
Order_Amount    14589.82284
Country               India
Name: 971, dtype: object
Product_Name         Laptop
Order_Amount    1497.941676
Country               India
Name: 972, dtype: object
Product_Name       Mobile
Order_Amount    2000000.0
Country             India
Name: 990, dtype: object
Product_Name           Shoes
Order_Amount    99224.742404
Country                India
Name: 995, dtype: object
Product_Name     Headphones
Order_Amount    2858.844121
Country               India
Name: 1035, dtype: object
Product_Name       Mobile
Order_Amount    2000000.0
Country             India
Name: 1044, dtype: object
Product_Name      Headphones
Order_Amount    14501.590033
Country                India
Name: 1052, dtype: object
Product_Name        Watch
Order_Amount    2000000.0
Country             India
Name: 1072, dtype: object
Product_Name       Mobile
Order_Amount    2000000.0
Country             India
Name: 1088, dtype: object
Product_Name          Camera
Order_Amount    45101.994125
Country                India
Name: 1100, dtype: object
Product_Name        Backpack
Order_Amount    84497.123652
Country                India
Name: 1103, dtype: object
Product_Name        Watch
Order_Amount    2000000.0
Country             India
Name: 1124, dtype: object
Product_Name       Camera
Order_Amount    2000000.0
Country             India
Name: 1126, dtype: object
Product_Name     Backpack
Order_Amount    2000000.0
Country             India
Name: 1127, dtype: object
Product_Name          Camera
Order_Amount    69878.232892
Country                India
Name: 1135, dtype: object
Product_Name        Shoes
Order_Amount    2000000.0
Country             India
Name: 1146, dtype: object
Product_Name        Backpack
Order_Amount    62553.664956
Country                India
Name: 1168, dtype: object
Product_Name          Camera
Order_Amount    26345.529967
Country                India
Name: 1180, dtype: object
Product_Name      Headphones
Order_Amount    33688.974702
Country                India
Name: 1193, dtype: object
Product_Name        Watch
Order_Amount    2000000.0
Country             India
Name: 1195, dtype: object
Product_Name          Shoes
Order_Amount    3844.846118
Country               India
Name: 1234, dtype: object
Product_Name        Shoes
Order_Amount    2000000.0
Country             India
Name: 1244, dtype: object
Product_Name          Laptop
Order_Amount    24829.674273
Country                India
Name: 1262, dtype: object
Product_Name           Shoes
Order_Amount    95454.153243
Country                India
Name: 1278, dtype: object
Product_Name       Mobile
Order_Amount    2000000.0
Country             India
Name: 1285, dtype: object
Product_Name     Backpack
Order_Amount    2000000.0
Country             India
Name: 1293, dtype: object
Product_Name    Headphones
Order_Amount     2000000.0
Country              India
Name: 1302, dtype: object
Product_Name          Laptop
Order_Amount    17957.974497
Country                India
Name: 1304, dtype: object
Product_Name       Laptop
Order_Amount    2000000.0
Country             India
Name: 1338, dtype: object
Product_Name           Shoes
Order_Amount    96256.617788
Country                India
Name: 1348, dtype: object
Product_Name          Camera
Order_Amount    45408.356966
Country                India
Name: 1381, dtype: object
Product_Name         Laptop
Order_Amount    5021.147398
Country               India
Name: 1383, dtype: object
Product_Name    Headphones
Order_Amount     2000000.0
Country              India
Name: 1418, dtype: object
Product_Name       Laptop
Order_Amount    2000000.0
Country             India
Name: 1430, dtype: object
Product_Name         Watch
Order_Amount    8744.42465
Country              India
Name: 1480, dtype: object
Product_Name        Shoes
Order_Amount    2000000.0
Country             India
Name: 1584, dtype: object
Product_Name          Shoes
Order_Amount    8168.541864
Country               India
Name: 1604, dtype: object
Product_Name         Mobile
Order_Amount    34641.84536
Country               India
Name: 1625, dtype: object
Product_Name     Backpack
Order_Amount    2000000.0
Country             India
Name: 1637, dtype: object
Product_Name        Shoes
Order_Amount    2000000.0
Country             India
Name: 1656, dtype: object
Product_Name        Backpack
Order_Amount    26140.772727
Country                India
Name: 1678, dtype: object
Product_Name       Mobile
Order_Amount    2000000.0
Country             India
Name: 1725, dtype: object
Product_Name          Camera
Order_Amount    74171.800937
Country                India
Name: 1727, dtype: object
Product_Name       Laptop
Order_Amount    2000000.0
Country             India
Name: 1756, dtype: object
Product_Name    Headphones
Order_Amount     2000000.0
Country              India
Name: 1757, dtype: object
Product_Name        Shoes
Order_Amount    2000000.0
Country             India
Name: 1759, dtype: object
Product_Name     Backpack
Order_Amount    2000000.0
Country             India
Name: 1812, dtype: object
Product_Name        Shoes
Order_Amount    2000000.0
Country             India
Name: 1846, dtype: object
Product_Name    Headphones
Order_Amount    6437.31231
Country              India
Name: 1885, dtype: object
Product_Name       Laptop
Order_Amount    2000000.0
Country             India
Name: 1962, dtype: object
Product_Name     Backpack
Order_Amount    2000000.0
Country             India
Name: 1966, dtype: object
Product_Name    Headphones
Order_Amount     2000000.0
Country              India
Name: 2022, dtype: object
Product_Name          Laptop
Order_Amount    70024.195336
Country                India
Name: 2036, dtype: object
Product_Name     Backpack
Order_Amount    2000000.0
Country             India
Name: 2050, dtype: object
Product_Name         Camera
Order_Amount    87662.36369
Country               India
Name: 2067, dtype: object
Product_Name    Headphones
Order_Amount     2000000.0
Country              India
Name: 2068, dtype: object
Product_Name        Watch
Order_Amount    2000000.0
Country             India
Name: 2077, dtype: object
Product_Name          Laptop
Order_Amount    63551.610348
Country                India
Name: 2128, dtype: object
Product_Name          Laptop
Order_Amount    23614.331138
Country                India
Name: 2145, dtype: object
Product_Name           Watch
Order_Amount    43857.205118
Country                India
Name: 2158, dtype: object
Product_Name        Shoes
Order_Amount    2000000.0
Country             India
Name: 2186, dtype: object
Product_Name          Mobile
Order_Amount    15330.981193
Country                India
Name: 2218, dtype: object
Product_Name       Camera
Order_Amount    2000000.0
Country             India
Name: 2226, dtype: object
Product_Name        Watch
Order_Amount    2000000.0
Country             India
Name: 2236, dtype: object
Product_Name    Headphones
Order_Amount     2000000.0
Country              India
Name: 2257, dtype: object
Product_Name    Headphones
Order_Amount     2000000.0
Country              India
Name: 2326, dtype: object
Product_Name           Watch
Order_Amount    21974.408277
Country                India
Name: 2345, dtype: object
Product_Name        Shoes
Order_Amount    2000000.0
Country             India
Name: 2356, dtype: object
Product_Name        Watch
Order_Amount    2000000.0
Country             India
Name: 2360, dtype: object
Product_Name        Watch
Order_Amount    2000000.0
Country             India
Name: 2362, dtype: object
Product_Name          Camera
Order_Amount    50507.195943
Country                India
Name: 2367, dtype: object
Product_Name        Watch
Order_Amount    2000000.0
Country             India
Name: 2376, dtype: object
Product_Name       Camera
Order_Amount    2000000.0
Country             India
Name: 2390, dtype: object
Product_Name    Headphones
Order_Amount     2000000.0
Country              India
Name: 2547, dtype: object
Product_Name    Headphones
Order_Amount     2000000.0
Country              India
Name: 2594, dtype: object
Product_Name        Shoes
Order_Amount    2000000.0
Country             India
Name: 2596, dtype: object
Product_Name       Mobile
Order_Amount    2000000.0
Country             India
Name: 2652, dtype: object
Product_Name       Mobile
Order_Amount    2000000.0
Country             India
Name: 2701, dtype: object
Product_Name       Camera
Order_Amount    2000000.0
Country             India
Name: 2719, dtype: object
Product_Name        Shoes
Order_Amount    2000000.0
Country             India
Name: 2720, dtype: object
Product_Name        Watch
Order_Amount    2000000.0
Country             India
Name: 2774, dtype: object
Product_Name     Backpack
Order_Amount    2000000.0
Country             India
Name: 2794, dtype: object
Product_Name         Mobile
Order_Amount    88773.03503
Country               India
Name: 2815, dtype: object
Product_Name           Shoes
Order_Amount    70019.498505
Country                India
Name: 2858, dtype: object
Product_Name          Mobile
Order_Amount    41298.432514
Country                India
Name: 2985, dtype: object
Product_Name       Laptop
Order_Amount    2000000.0
Country             India
Name: 2989, dtype: object
Product_Name      Headphones
Order_Amount    41214.492775
Country                India
Name: 2993, dtype: object
Product_Name        Backpack
Order_Amount    89033.879583
Country                India
Name: 3018, dtype: object
Product_Name        Shoes
Order_Amount    2000000.0
Country             India
Name: 3090, dtype: object
Product_Name         Mobile
Order_Amount    58445.61301
Country               India
Name: 3113, dtype: object
Product_Name          Laptop
Order_Amount    36995.413929
Country                India
Name: 3115, dtype: object
Product_Name           Shoes
Order_Amount    11865.914149
Country                India
Name: 3118, dtype: object
Product_Name          Laptop
Order_Amount    35241.100941
Country                India
Name: 3142, dtype: object
Product_Name      Headphones
Order_Amount    40352.242152
Country                India
Name: 3158, dtype: object
Product_Name       Camera
Order_Amount    2000000.0
Country             India
Name: 3369, dtype: object
Product_Name       Mobile
Order_Amount    2000000.0
Country             India
Name: 3441, dtype: object
Product_Name      Headphones
Order_Amount    59790.016447
Country                India
Name: 3464, dtype: object
Product_Name        Backpack
Order_Amount    20281.827618
Country                India
Name: 3501, dtype: object
Product_Name        Shoes
Order_Amount    2000000.0
Country             India
Name: 3531, dtype: object
Product_Name       Laptop
Order_Amount    2000000.0

6.	Fetch orders placed during holiday dates

In [ ]:
Holiday = '2022-01-15'
a[a['Order_Date'] =='2022-01-15']

,Order_ID,Customer_ID,Product_ID,Product_Name,Order_Amount,Payment_Mode,Order_Date,Shipping_Address,Quantity,Email,...,Discount,Delivery_Time,Status,Shipping_Fee,Tracking_Number,Billing_Address,Delivery_Date,Price,Category,temp_notes
4477,101962,1044,141,Mobile,2000000.0,Credit Card,2022-01-15,Bengaluru,2.0,jnoofqy@gmail.com,...,50,3,Pending,100,TRK1536,Mumbai,07/06/23,301.308863,Electronics,note1

7.	Fetch customers with more than 5 orders.

In [ ]:
v=a['Customer_ID'].value_counts()
for i in v.index :
  if v.loc[i] > 5:
    print(i,v[i])

1163 7
1015 7
1004 6
1036 6
1012 6
1039 6
1129 6

8.	Fetch orders with missing tracking number

In [ ]:
for i in a.index :
  if a.loc[i,'Tracking_Number'] == 'None' :
    a.loc[i]

In [ ]:
a

,Order_ID,Customer_ID,Product_ID,Product_Name,Order_Amount,Payment_Mode,Order_Date,Shipping_Address,Quantity,Email,...,Discount,Delivery_Time,Status,Shipping_Fee,Tracking_Number,Billing_Address,Delivery_Date,Price,Category,temp_notes
0,101126,1179,102,Camera,7.322619e+04,Credit Card,2023-10-12,Delhi,5.0,fmflokr@gmail.com,...,20,5,Pending,150,NaN,Bengaluru,13-08-2020,30950.579179,Fashion,temp
4,101367,1128,145,Camera,8.156460e+04,Debit Card,2024-05-25,Hyderabad,3.0,srkahlm@yahoo.com,...,50,1,Delivered,100,NaN,Delhi,2024/09/20,16394.129437,Accessories,NaN
7,101496,1189,138,Laptop,6.480424e+04,Credit Card,2022-04-11,unspecified,4.0,wyzpguy@gmail.com,...,5,3,Pending,150,TRK1663,Delhi,20-06-2022,20311.041319,Fashion,note1
13,100658,1003,44,Laptop,2.000000e+06,UPI,2020-05-12,unspecified,4.0,hdhzitl@gmail.com,...,50,1,Pending,100,NaN,Chennai,13/02/21,15423.711561,Accessories,note1
20,100496,1127,169,Headphones,2.000000e+06,Debit Card,2024-08-24,Chennai,2.0,biokraq@gmail.com,...,50,3,Delivered,50,TRK4913,Bengaluru,12-10-2018,10886.538161,Fashion,temp
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4855,101534,1153,13,Headphones,7.668544e+02,Cash,NaN,Mumbai,4.0,ysqrxbq@yahoo.com,...,50,1,Delivered,100,TRK2416,Bengaluru,2022/01/03,43434.001308,Accessories,NaN
4857,100575,1004,179,Mobile,2.000000e+06,Credit Card,2020-08-13,Bengaluru,5.0,kcnkctv@hotmail.com,...,50,1,Pending,100,TRK4843,Chennai,08-12-2023,37538.792046,Electronics,NaN
4874,100053,1039,187,Laptop,2.380147e+04,Credit Card,NaN,Bengaluru,5.0,bdwuiis@gmail.com,...,5,5,Cancelled,100,NaN,Chennai,17/03/19,9214.851110,Electronics,NaN
4905,100304,1091,99,Laptop,2.000000e+06,UPI,2021-10-18,Mumbai,2.0,nrfnrfg@hotmail.com,...,20,3,Pending,150,NaN,Mumbai,08/07/23,27592.992544,Electronics,note1
4984,100832,1064,151,Mobile,8.000390e+04,Credit Card,2021-09-25,Chennai,5.0,hzggukg@gmal.com,...,5,3,Delivered,50,TRK1565,Chennai,23/12/21,29784.570278,Accessories,-

9.	Fetch returned orders.

In [ ]:
for i in a.index :
  if a.loc[i,'Status']=='Cancelled' :
    print(a.loc[i][['Product_Name','Order_ID','Status']])

Product_Name     Backpack
Order_ID           100512
Status          Cancelled
Name: 40, dtype: object
Product_Name       Camera
Order_ID           100935
Status          Cancelled
Name: 58, dtype: object
Product_Name       Laptop
Order_ID           100199
Status          Cancelled
Name: 101, dtype: object
Product_Name        Watch
Order_ID           101600
Status          Cancelled
Name: 115, dtype: object
Product_Name    Headphones
Order_ID            101457
Status           Cancelled
Name: 136, dtype: object
Product_Name        Shoes
Order_ID           100164
Status          Cancelled
Name: 139, dtype: object
Product_Name     Backpack
Order_ID           101913
Status          Cancelled
Name: 161, dtype: object
Product_Name       Laptop
Order_ID           100415
Status          Cancelled
Name: 184, dtype: object
Product_Name        Shoes
Order_ID           100903
Status          Cancelled
Name: 198, dtype: object
Product_Name       Laptop
Order_ID           100830
Status          Cancelled
Name: 200, dtype: object
Product_Name    Headphones
Order_ID            100855
Status           Cancelled
Name: 207, dtype: object
Product_Name        Shoes
Order_ID           101498
Status          Cancelled
Name: 234, dtype: object
Product_Name       Laptop
Order_ID           101164
Status          Cancelled
Name: 306, dtype: object
Product_Name    Headphones
Order_ID            101933
Status           Cancelled
Name: 345, dtype: object
Product_Name     Backpack
Order_ID           101176
Status          Cancelled
Name: 367, dtype: object
Product_Name       Laptop
Order_ID           101315
Status          Cancelled
Name: 372, dtype: object
Product_Name    Headphones
Order_ID            101170
Status           Cancelled
Name: 432, dtype: object
Product_Name       Mobile
Order_ID           101738
Status          Cancelled
Name: 464, dtype: object
Product_Name    Headphones
Order_ID            100617
Status           Cancelled
Name: 493, dtype: object
Product_Name        Watch
Order_ID           100426
Status          Cancelled
Name: 524, dtype: object
Product_Name        Watch
Order_ID           101138
Status          Cancelled
Name: 540, dtype: object
Product_Name       Laptop
Order_ID           100465
Status          Cancelled
Name: 584, dtype: object
Product_Name       Mobile
Order_ID           101553
Status          Cancelled
Name: 610, dtype: object
Product_Name        Watch
Order_ID           101443
Status          Cancelled
Name: 616, dtype: object
Product_Name        Watch
Order_ID           100864
Status          Cancelled
Name: 641, dtype: object
Product_Name       Mobile
Order_ID           100624
Status          Cancelled
Name: 709, dtype: object
Product_Name       Mobile
Order_ID           101504
Status          Cancelled
Name: 771, dtype: object
Product_Name        Watch
Order_ID           101205
Status          Cancelled
Name: 833, dtype: object
Product_Name        Watch
Order_ID           100200
Status          Cancelled
Name: 907, dtype: object
Product_Name       Mobile
Order_ID           100586
Status          Cancelled
Name: 913, dtype: object
Product_Name     Backpack
Order_ID           101985
Status          Cancelled
Name: 1043, dtype: object
Product_Name    Headphones
Order_ID            100562
Status           Cancelled
Name: 1048, dtype: object
Product_Name        Watch
Order_ID           100986
Status          Cancelled
Name: 1121, dtype: object
Product_Name        Watch
Order_ID           101482
Status          Cancelled
Name: 1124, dtype: object
Product_Name       Camera
Order_ID           101679
Status          Cancelled
Name: 1126, dtype: object
Product_Name     Backpack
Order_ID           101701
Status          Cancelled
Name: 1127, dtype: object
Product_Name        Shoes
Order_ID           100063
Status          Cancelled
Name: 1146, dtype: object
Product_Name        Shoes
Order_ID           100328
Status          Cancelled
Name: 1191, dtype: object
Product_Name    Headphones
Order_ID            101730
Status           Cancelled
Name: 1193, dtype: object
Product_Name        Watch
Order_ID           100670
Status          Cancelled
Name: 1195, dtype: object
Product_Name     Backpack
Order_ID           101776
Status          Cancelled
Name: 1219, dtype: object
Product_Name       Laptop
Order_ID           101928
Status          Cancelled
Name: 1240, dtype: object
Product_Name        Shoes
Order_ID           100671
Status          Cancelled
Name: 1244, dtype: object
Product_Name       Camera
Order_ID           101203
Status          Cancelled
Name: 1259, dtype: object
Product_Name       Laptop
Order_ID           101681
Status          Cancelled
Name: 1262, dtype: object
Product_Name    Headphones
Order_ID            101266
Status           Cancelled
Name: 1302, dtype: object
Product_Name        Watch
Order_ID           101274
Status          Cancelled
Name: 1313, dtype: object
Product_Name       Camera
Order_ID           100547
Status          Cancelled
Name: 1327, dtype: object
Product_Name    Headphones
Order_ID            101202
Status           Cancelled
Name: 1353, dtype: object
Product_Name        Shoes
Order_ID           100564
Status          Cancelled
Name: 1368, dtype: object
Product_Name       Camera
Order_ID           100080
Status          Cancelled
Name: 1381, dtype: object
Product_Name    Headphones
Order_ID            101239
Status           Cancelled
Name: 1444, dtype: object
Product_Name        Shoes
Order_ID           100754
Status          Cancelled
Name: 1461, dtype: object
Product_Name        Watch
Order_ID           101028
Status          Cancelled
Name: 1480, dtype: object
Product_Name        Shoes
Order_ID           100103
Status          Cancelled
Name: 1596, dtype: object
Product_Name    Headphones
Order_ID            101369
Status           Cancelled
Name: 1623, dtype: object
Product_Name       Mobile
Order_ID           101771
Status          Cancelled
Name: 1625, dtype: object
Product_Name        Watch
Order_ID           101074
Status          Cancelled
Name: 1665, dtype: object
Product_Name       Laptop
Order_ID           101177
Status          Cancelled
Name: 1668, dtype: object
Product_Name       Laptop
Order_ID           100774
Status          Cancelled
Name: 1680, dtype: object
Product_Name        Shoes
Order_ID           101779
Status          Cancelled
Name: 1759, dtype: object
Product_Name        Shoes
Order_ID           101341
Status          Cancelled
Name: 1774, dtype: object
Product_Name       Camera
Order_ID           101724
Status          Cancelled
Name: 1802, dtype: object
Product_Name    Headphones
Order_ID            100672
Status           Cancelled
Name: 1885, dtype: object
Product_Name       Mobile
Order_ID           100302
Status          Cancelled
Name: 1931, dtype: object
Product_Name       Laptop
Order_ID           100603
Status          Cancelled
Name: 1962, dtype: object
Product_Name     Backpack
Order_ID           100777
Status          Cancelled
Name: 1966, dtype: object
Product_Name       Mobile
Order_ID           100567
Status          Cancelled
Name: 1967, dtype: object
Product_Name    Headphones
Order_ID            101795
Status           Cancelled
Name: 1976, dtype: object
Product_Name       Camera
Order_ID           100436
Status          Cancelled
Name: 1982, dtype: object
Product_Name        Watch
Order_ID           100092
Status          Cancelled
Name: 1988, dtype: object
Product_Name    Headphones
Order_ID            101815
Status           Cancelled
Name: 2022, dtype: object
Product_Name     Backpack
Order_ID           101576
Status          Cancelled
Name: 2050, dtype: object
Product_Name       Laptop
Order_ID           101789
Status          Cancelled
Name: 2128, dtype: object
Product_Name       Laptop
Order_ID           100652
Status          Cancelled
Name: 2134, dtype: object
Product_Name        Watch
Order_ID           101433
Status          Cancelled
Name: 2158, dtype: object
Product_Name        Watch
Order_ID           101740
Status          Cancelled
Name: 2310, dtype: object
Product_Name        Watch
Order_ID           100871
Status          Cancelled
Name: 2360, dtype: object
Product_Name       Camera
Order_ID           101173
Status          Cancelled
Name: 2367, dtype: object
Product_Name       Mobile
Order_ID           101308
Status          Cancelled
Name: 2389, dtype: object
Product_Name       Camera
Order_ID           100042
Status          Cancelled
Name: 2390, dtype: object
Product_Name        Watch
Order_ID           100443
Status          Cancelled
Name: 2396, dtype: object
Product_Name     Backpack
Order_ID           100566
Status          Cancelled
Name: 2423, dtype: object
Product_Name       Mobile
Order_ID           100084
Status          Cancelled
Name: 2652, dtype: object
Product_Name        Shoes
Order_ID           101489
Status          Cancelled
Name: 2720, dtype: object
Product_Name       Camera
Order_ID           100125
Status          Cancelled
Name: 2924, dtype: object
Product_Name       Laptop
Order_ID           101927
Status          Cancelled
Name: 3115, dtype: object
Product_Name       Camera
Order_ID           100859
Status          Cancelled
Name: 3369, dtype: object
Product_Name       Camera
Order_ID           100291
Status          Cancelled
Name: 3385, dtype: object
Product_Name     Backpack
Order_ID           100561
Status          Cancelled
Name: 3449, dtype: object
Product_Name       Laptop
Order_ID           101363
Status          Cancelled
Name: 3547, dtype: object
Product_Name    Headphones
Order_ID            101158
Status           Cancelled
Name: 3587, dtype: object
Product_Name        Shoes
Order_ID           100245
Status          Cancelled
Name: 3647, dtype: object
Product_Name     Backpack
Order_ID           100091
Status          Cancelled
Name: 4037, dtype: object
Product_Name       Camera
Order_ID           100840
Status          Cancelled
Name: 4065, dtype: object
Product_Name    Headphones
Order_ID            100922
Status           Cancelled
Name: 4253, dtype: object
Product_Name       Laptop
Order_ID           101316
Status          Cancelled
Name: 4601, dtype: object
Product_Name       Laptop
Order_ID           100053
Status          Cancelled
Name: 4874, dtype: object

10.	Fetch orders with mismatched billing & shipping addresses

In [ ]:
for i in a.index :
  if a.loc[i,'Shipping_Address'] != a.loc[i,'Billing_Address'] :
    print(a.loc[i][['Product_Name','Shipping_Address','Billing_Address']])

Product_Name           Camera
Shipping_Address        Delhi
Billing_Address     Bengaluru
Name: 0, dtype: object
Product_Name           Camera
Shipping_Address    Hyderabad
Billing_Address         Delhi
Name: 4, dtype: object
Product_Name             Laptop
Shipping_Address    unspecified
Billing_Address           Delhi
Name: 7, dtype: object
Product_Name             Laptop
Shipping_Address    unspecified
Billing_Address         Chennai
Name: 13, dtype: object
Product_Name        Headphones
Shipping_Address       Chennai
Billing_Address      Bengaluru
Name: 20, dtype: object
Product_Name        Headphones
Shipping_Address     Bengaluru
Billing_Address         Mumbai
Name: 23, dtype: object
Product_Name           Laptop
Shipping_Address    Hyderabad
Billing_Address        Mumbai
Name: 24, dtype: object
Product_Name           Laptop
Shipping_Address    Hyderabad
Billing_Address         Delhi
Name: 26, dtype: object
Product_Name            Watch
Shipping_Address    Hyderabad
Billing_Address         Delhi
Name: 28, dtype: object
Product_Name            Watch
Shipping_Address    Bengaluru
Billing_Address        Mumbai
Name: 33, dtype: object
Product_Name         Backpack
Shipping_Address      Chennai
Billing_Address     Bengaluru
Name: 34, dtype: object
Product_Name        Headphones
Shipping_Address       Chennai
Billing_Address         Mumbai
Name: 35, dtype: object
Product_Name           Mobile
Shipping_Address    Hyderabad
Billing_Address        Mumbai
Name: 39, dtype: object
Product_Name              Shoes
Shipping_Address    unspecified
Billing_Address           Delhi
Name: 42, dtype: object
Product_Name        Camera
Shipping_Address     Delhi
Billing_Address     Mumbai
Name: 43, dtype: object
Product_Name            Shoes
Shipping_Address    Hyderabad
Billing_Address        Mumbai
Name: 44, dtype: object
Product_Name              Shoes
Shipping_Address    unspecified
Billing_Address       Bengaluru
Name: 47, dtype: object
Product_Name        Backpack
Shipping_Address      Mumbai
Billing_Address        Delhi
Name: 52, dtype: object
Product_Name        Camera
Shipping_Address    Mumbai
Billing_Address      Delhi
Name: 58, dtype: object
Product_Name            Shoes
Shipping_Address    Bengaluru
Billing_Address        Mumbai
Name: 66, dtype: object
Product_Name              Watch
Shipping_Address    unspecified
Billing_Address         Chennai
Name: 67, dtype: object
Product_Name           Laptop
Shipping_Address    Bengaluru
Billing_Address       Chennai
Name: 69, dtype: object
Product_Name         Headphones
Shipping_Address    unspecified
Billing_Address       Bengaluru
Name: 71, dtype: object
Product_Name         Camera
Shipping_Address    Chennai
Billing_Address       Delhi
Name: 86, dtype: object
Product_Name             Camera
Shipping_Address    unspecified
Billing_Address          Mumbai
Name: 87, dtype: object
Product_Name             Mobile
Shipping_Address    unspecified
Billing_Address          Mumbai
Name: 94, dtype: object
Product_Name           Laptop
Shipping_Address    Hyderabad
Billing_Address     Bengaluru
Name: 101, dtype: object
Product_Name           Camera
Shipping_Address    Hyderabad
Billing_Address       Chennai
Name: 113, dtype: object
Product_Name            Watch
Shipping_Address    Hyderabad
Billing_Address     Bengaluru
Name: 115, dtype: object
Product_Name         Backpack
Shipping_Address       Mumbai
Billing_Address     Bengaluru
Name: 120, dtype: object
Product_Name           Mobile
Shipping_Address    Hyderabad
Billing_Address        Mumbai
Name: 132, dtype: object
Product_Name           Laptop
Shipping_Address    Hyderabad
Billing_Address        Mumbai
Name: 133, dtype: object
Product_Name           Laptop
Shipping_Address        Delhi
Billing_Address     Bengaluru
Name: 135, dtype: object
Product_Name         Headphones
Shipping_Address    unspecified
Billing_Address          Mumbai
Name: 136, dtype: object
Product_Name            Shoes
Shipping_Address    Bengaluru
Billing_Address       Chennai
Name: 137, dtype: object
Product_Name            Shoes
Shipping_Address    Hyderabad
Billing_Address       Chennai
Name: 139, dtype: object
Product_Name         Camera
Shipping_Address    Chennai
Billing_Address       Delhi
Name: 141, dtype: object
Product_Name        Backpack
Shipping_Address     Chennai
Billing_Address        Delhi
Name: 142, dtype: object
Product_Name            Shoes
Shipping_Address    Bengaluru
Billing_Address       Chennai
Name: 157, dtype: object
Product_Name          Shoes
Shipping_Address    Chennai
Billing_Address      Mumbai
Name: 179, dtype: object
Product_Name          Watch
Shipping_Address      Delhi
Billing_Address     Chennai
Name: 187, dtype: object
Product_Name        Backpack
Shipping_Address       Delhi
Billing_Address      Chennai
Name: 192, dtype: object
Product_Name            Shoes
Shipping_Address    Bengaluru
Billing_Address        Mumbai
Name: 198, dtype: object
Product_Name            Shoes
Shipping_Address      Chennai
Billing_Address     Bengaluru
Name: 199, dtype: object
Product_Name         Laptop
Shipping_Address    Chennai
Billing_Address       Delhi
Name: 200, dtype: object
Product_Name        Headphones
Shipping_Address       Chennai
Billing_Address      Bengaluru
Name: 207, dtype: object
Product_Name         Backpack
Shipping_Address    Hyderabad
Billing_Address         Delhi
Name: 210, dtype: object
Product_Name             Mobile
Shipping_Address    unspecified
Billing_Address           Delhi
Name: 218, dtype: object
Product_Name            Shoes
Shipping_Address    Bengaluru
Billing_Address        Mumbai
Name: 225, dtype: object
Product_Name             Mobile
Shipping_Address    unspecified
Billing_Address          Mumbai
Name: 228, dtype: object
Product_Name            Shoes
Shipping_Address    Hyderabad
Billing_Address     Bengaluru
Name: 234, dtype: object
Product_Name           Mobile
Shipping_Address    Bengaluru
Billing_Address       Chennai
Name: 239, dtype: object
Product_Name              Watch
Shipping_Address    unspecified
Billing_Address       Bengaluru
Name: 245, dtype: object
Product_Name           Laptop
Shipping_Address    Bengaluru
Billing_Address         Delhi
Name: 254, dtype: object
Product_Name            Watch
Shipping_Address        Delhi
Billing_Address     Bengaluru
Name: 255, dtype: object
Product_Name        Headphones
Shipping_Address     Hyderabad
Billing_Address         Mumbai
Name: 263, dtype: object
Product_Name        Backpack
Shipping_Address      Mumbai
Billing_Address        Delhi
Name: 270, dtype: object
Product_Name        Backpack
Shipping_Address       Delhi
Billing_Address       Mumbai
Name: 284, dtype: object
Product_Name         Mobile
Shipping_Address      Delhi
Billing_Address     Chennai
Name: 285, dtype: object
Product_Name           Mobile
Shipping_Address    Hyderabad
Billing_Address     Bengaluru
Name: 287, dtype: object
Product_Name        Mobile
Shipping_Address     Delhi
Billing_Address     Mumbai
Name: 291, dtype: object
Product_Name            Shoes
Shipping_Address    Hyderabad
Billing_Address         Delhi
Name: 305, dtype: object
Product_Name         Laptop
Shipping_Address    Chennai
Billing_Address       Delhi
Name: 306, dtype: object
Product_Name           Camera
Shipping_Address       Mumbai
Billing_Address     Bengaluru
Name: 307, dtype: object
Product_Name           Mobile
Shipping_Address    Hyderabad
Billing_Address         Delhi
Name: 310, dtype: object
Product_Name           Backpack
Shipping_Address    unspecified
Billing_Address          Mumbai
Name: 325, dtype: object
Product_Name           Camera
Shipping_Address    Bengaluru
Billing_Address       Chennai
Name: 329, dtype: object
Product_Name         Backpack
Shipping_Address      Chennai
Billing_Address     Bengaluru
Name: 332, dtype: object
Product_Name            Shoes
Shipping_Address    Hyderabad
Billing_Address     Bengaluru
Name: 337, dtype: object
Product_Name         Headphones
Shipping_Address    unspecified
Billing_Address          Mumbai
Name: 345, dtype: object
Product_Name        Laptop
Shipping_Address     Delhi
Billing_Address     Mumbai
Name: 346, dtype: object
Product_Name              Shoes
Shipping_Address    unspecified
Billing_Address       Bengaluru
Name: 355, dtype: object
Product_Name         Laptop
Shipping_Address      Delhi
Billing_Address     Chennai
Name: 356, dtype: object
Product_Name           Camera
Shipping_Address    Hyderabad
Billing_Address        Mumbai
Name: 358, dtype: object
Product_Name          Shoes
Shipping_Address    Chennai
Billing_Address       Delhi
Name: 362, dtype: object
Product_Name         Backpack
Shipping_Address    Hyderabad
Billing_Address       Chennai
Name: 367, dtype: object
Product_Name           Laptop
Shipping_Address    Hyderabad
Billing_Address         Delhi
Name: 372, dtype: object
Product_Name        Mobile
Shipping_Address     Delhi
Billing_Address     Mumbai
Name: 373, dtype: object
Product_Name        Headphones
Shipping_Address     Bengaluru
Billing_Address          Delhi
Name: 378, dtype: object
Product_Name           Mobile
Shipping_Address    Hyderabad
Billing_Address         Delhi
Name: 383, dtype: object
Product_Name            Shoes
Shipping_Address       Mumbai
Billing_Address     Bengaluru
Name: 389, dtype: object
Product_Name            Shoes
Shipping_Address    Hyderabad
Billing_Address         Delhi
Name: 403, dtype: object
Product_Name          Shoes
Shipping_Address      Delhi
Billing_Address     Chennai
Name: 405, dtype: object
Product_Name           Laptop
Shipping_Address       Mumbai
Billing_Address     Bengaluru
Name: 410, dtype: object
Product_Name           Camera
Shipping_Address    Bengaluru
Billing_Address        Mumbai
Name: 425, dtype: object
Product_Name           Laptop
Shipping_Address    Hyderabad
Billing_Address       Chennai
Name: 426, dtype: object
Product_Name        Headphones
Shipping_Address     Hyderabad
Billing_Address        Chennai
Name: 429, dtype: object
Product_Name            Watch
Shipping_Address    Hyderabad
Billing_Address     Bengaluru
Name: 430, dtype: object
Product_Name           Mobile
Shipping_Address        Delhi
Billing_Address     Bengaluru
Name: 431, dtype: object
Product_Name         Laptop
Shipping_Address    Chennai
Billing_Address      Mumbai
Name: 435, dtype: object
Product_Name              Watch
Shipping_Address    unspecified
Billing_Address          Mumbai
Name: 436, dtype: object
Product_Name           Laptop
Shipping_Address    Hyderabad
Billing_Address        Mumbai
Name: 441, dtype: object
Product_Name        Headphones
Shipping_Address        Mumbai
Billing_Address          Delhi
Name: 449, dtype: object
Product_Name         Mobile
Shipping_Address    Chennai
Billing_Address       Delhi
Name: 464, dtype: object
Product_Name           Mobile
Shipping_Address    Hyderabad
Billing_Address       Chennai
Name: 465, dtype: object
Product_Name             Laptop
Shipping_Address    unspecified
Billing_Address           Delhi
Name: 469, dtype: object
Product_Name            Shoes
Shipping_Address    Hyderabad
Billing_Address         Delhi
Name: 471, dtype: object
Product_Name             Mobile
Shipping_Address    unspecified
Billing_Address          Mumbai
Name: 490, dtype: object
Product_Name             Camera
Shipping_Address    unspecified
Billing_Address         Chennai
Name: 510, dtype: object
Product_Name         Laptop
Shipping_Address    Chennai
Billing_Address      Mumbai
Name: 514, dtype: object
Product_Name        Headphones
Shipping_Address     Hyderabad
Billing_Address          Delhi
Name: 517, dtype: object
Product_Name            Watch
Shipping_Address    Bengaluru
Billing_Address         Delhi
Name: 524, dtype: object
Product_Name              Watch
Shipping_Address    unspecified
Billing_Address       Bengaluru
Name: 529, dtype: object
Product_Name             Mobile
Shipping_Address    unspecified
Billing_Address       Bengaluru
Name: 538, dtype: object
Product_Name            Watch
Shipping_Address    Bengaluru
Billing_Address       Chennai
Name: 540, dtype: object
Product_Name           Mobile
Shipping_Address    Bengaluru
Billing_Address         Delhi
Name: 546, dtype: object
Product_Name           Backpack
Shipping_Address    unspecified
Billing_Address         Chennai
Name: 550, dtype: object
Product_Name           Camera
Shipping_Address    Hyderabad
Billing_Address        Mumbai
Name: 552, dtype: object
Product_Name         Camera
Shipping_Address    Chennai
Billing_Address      Mumbai
Name: 568, dtype: object
Product_Name         Laptop
Shipping_Address     Mumbai
Billing_Address     Chennai
Name: 584, dtype: object
Product_Name              Shoes
Shipping_Address    unspecified
Billing_Address         Chennai
Name: 599, dtype: object
Product_Name           Mobile
Shipping_Address    Hyderabad
Billing_Address     Bengaluru
Name: 603, dtype: object
Product_Name             Mobile
Shipping_Address    unspecified
Billing_Address       Bengaluru
Name: 610, dtype: object
Product_Name         Backpack
Shipping_Address    Bengaluru
Billing_Address        Mumbai
Name: 615, dtype: object
Product_Name          Watch
Shipping_Address      Delhi
Billing_Address     Chennai
Name: 616, dtype: object
Product_Name         Mobile
Shipping_Address     Mumbai
Billing_Address     Chennai
Name: 620, dtype: object
Product_Name           Backpack
Shipping_Address    unspecified
Billing_Address           Delhi
Name: 629, dtype: object
Product_Name         Watch
Shipping_Address    Mumbai
Billing_Address      Delhi
Name: 641, dtype: object
Product_Name         Backpack
Shipping_Address    Bengaluru
Billing_Address        Mumbai
Name: 656, dtype: object
Product_Name        Backpack
Shipping_Address     Chennai
Billing_Address       Mumbai
Name: 660, dtype: object
Product_Name            Watch
Shipping_Address    Hyderabad
Billing_Address         Delhi
Name: 672, dtype: object
Product_Name           Camera
Shipping_Address    Bengaluru
Billing_Address         Delhi
Name: 674, dtype: object
Product_Name        Backpack
Shipping_Address       Delhi
Billing_Address       Mumbai
Name: 680, dtype: object
Product_Name          Shoes
Shipping_Address    Chennai
Billing_Address      Mumbai
Name: 686, dtype: object
Product_Name        Headphones
Shipping_Address         Delhi
Billing_Address         Mumbai
Name: 705, dtype: object
Product_Name           Mobile
Shipping_Address    Bengaluru
Billing_Address        Mumbai
Name: 709, dtype: object
Product_Name        Headphones
Shipping_Address     Hyderabad
Billing_Address        Chennai
Name: 717, dtype: object
Product_Name             Laptop
Shipping_Address    unspecified
Billing_Address       Bengaluru
Name: 728, dtype: object
Product_Name        Headphones
Shipping_Address     Bengaluru
Billing_Address        Chennai
Name: 730, dtype: object
Product_Name           Mobile
Shipping_Address    Hyderabad
Billing_Address     Bengaluru
Name: 749, dtype: object
Product_Name             Camera
Shipping_Address    unspecified
Billing_Address          Mumbai
Name: 759, dtype: object
Product_Name           Laptop
Shipping_Address    Hyderabad
Billing_Address     Bengaluru
Name: 777, dtype: object
Product_Name            Watch
Shipping_Address    Hyderabad
Billing_Address     Bengaluru
Name: 791, dtype: object
Product_Name         Camera
Shipping_Address    Chennai
Billing_Address       Delhi
Name: 795, dtype: object
Product_Name         Camera
Shipping_Address     Mumbai
Billing_Address     Chennai
Name: 806, dtype: object
Product_Name         Mobile
Shipping_Address      Delhi
Billing_Address     Chennai
Name: 814, dtype: object
Product_Name            Watch
Shipping_Address    Hyderabad
Billing_Address         Delhi
Name: 825, dtype: object
Product_Name           Backpack
Shipping_Address    unspecified
Billing_Address           Delhi
Name: 827, dtype: object
Product_Name              Watch
Shipping_Address    unspecified
Billing_Address         Chennai
Name: 833, dtype: object
Product_Name           Backpack
Shipping_Address    unspecified
Billing_Address       Bengaluru
Name: 835, dtype: object
Product_Name            Watch
Shipping_Address    Hyderabad
Billing_Address     Bengaluru
Name: 836, dtype: object
Product_Name           Camera
Shipping_Address    Hyderabad
Billing_Address     Bengaluru
Name: 838, dtype: object
Product_Name           Backpack
Shipping_Address    unspecified
Billing_Address          Mumbai
Name: 864, dtype: object
Product_Name         Mobile
Shipping_Address    Chennai
Billing_Address       Delhi
Name: 870, dtype: object
Product_Name           Camera
Shipping_Address    Hyderabad
Billing_Address       Chennai
Name: 877, dtype: object
Product_Name             Mobile
Shipping_Address    unspecified
Billing_Address       Bengaluru
Name: 895, dtype: object
Product_Name            Watch
Shipping_Address    Bengaluru
Billing_Address         Delhi
Name: 903, dtype: object
Product_Name         Watch
Shipping_Address    Mumbai
Billing_Address      Delhi
Name: 906, dtype: object
Product_Name          Watch
Shipping_Address    Chennai
Billing_Address       Delhi
Name: 907, dtype: object
Product_Name           Mobile
Shipping_Address    Bengaluru
Billing_Address       Chennai
Name: 913, dtype: object
Product_Name        Headphones
Shipping_Address     Bengaluru
Billing_Address          Delhi
Name: 930, dtype: object
Product_Name           Mobile
Shipping_Address        Delhi
Billing_Address     Bengaluru
Name: 936, dtype: object
Product_Name        Backpack
Shipping_Address     Chennai
Billing_Address       Mumbai
Name: 937, dtype: object
Product_Name             Mobile
Shipping_Address    unspecified
Billing_Address         Chennai
Name: 939, dtype: object
Product_Name        Headphones
Shipping_Address       Chennai
Billing_Address      Bengaluru
Name: 943, dtype: object
Product_Name         Laptop
Shipping_Address    Chennai
Billing_Address       Delhi
Name: 945, dtype: object
Product_Name        Laptop
Shipping_Address     Delhi
Billing_Address     Mumbai
Name: 946, dtype: object
Product_Name            Shoes
Shipping_Address    Hyderabad
Billing_Address     Bengaluru
Name: 954, dtype: object
Product_Name         Backpack
Shipping_Address    Hyderabad
Billing_Address       Chennai
Name: 956, dtype: object
Product_Name           Camera
Shipping_Address    Bengaluru
Billing_Address       Chennai
Name: 957, dtype: object
Product_Name         Backpack
Shipping_Address    Hyderabad
Billing_Address       Chennai
Name: 961, dtype: object
Product_Name              Watch
Shipping_Address    unspecified
Billing_Address           Delhi
Name: 967, dtype: object
Product_Name        Headphones
Shipping_Address        Mumbai
Billing_Address      Bengaluru
Name: 971, dtype: object
Product_Name             Laptop
Shipping_Address    unspecified
Billing_Address           Delhi
Name: 972, dtype: object
Product_Name              Shoes
Shipping_Address    unspecified
Billing_Address          Mumbai
Name: 973, dtype: object
Product_Name         Mobile
Shipping_Address      Delhi
Billing_Address     Chennai
Name: 990, dtype: object
Product_Name            Shoes
Shipping_Address    Hyderabad
Billing_Address         Delhi
Name: 995, dtype: object
Product_Name            Watch
Shipping_Address       Mumbai
Billing_Address     Bengaluru
Name: 1000, dtype: object
Product_Name            Shoes
Shipping_Address    Hyderabad
Billing_Address       Chennai
Name: 1013, dtype: object
Product_Name         Laptop
Shipping_Address     Mumbai
Billing_Address     Chennai
Name: 1027, dtype: object
Product_Name        Headphones
Shipping_Address     Hyderabad
Billing_Address         Mumbai
Name: 1035, dtype: object
Product_Name            Shoes
Shipping_Address    Hyderabad
Billing_Address       Chennai
Name: 1041, dtype: object
Product_Name           Backpack
Shipping_Address    unspecified
Billing_Address          Mumbai
Name: 1043, dtype: object
Product_Name        Headphones
Shipping_Address     Hyderabad
Billing_Address         Mumbai

E. Calculated Columns / Transformations

1.	Add Total_Price = Price × Quantity − Discount

In [ ]:
a['Total_Price']=a['Price'] * a['Quantity'] - a['Discount']

In [ ]:
a

,Order_ID,Customer_ID,Product_ID,Product_Name,Order_Amount,Payment_Mode,Order_Date,Shipping_Address,Quantity,Email,...,Delivery_Time,Status,Shipping_Fee,Tracking_Number,Billing_Address,Delivery_Date,Price,Category,temp_notes,Total_Price
0,101126,1179,102,Camera,7.322619e+04,Credit Card,2023-10-12,Delhi,5.0,fmflokr@gmail.com,...,5,Pending,150,NaN,Bengaluru,13-08-2020,30950.579179,Fashion,temp,154732.895897
4,101367,1128,145,Camera,8.156460e+04,Debit Card,2024-05-25,Hyderabad,3.0,srkahlm@yahoo.com,...,1,Delivered,100,NaN,Delhi,2024/09/20,16394.129437,Accessories,NaN,49132.388311
7,101496,1189,138,Laptop,6.480424e+04,Credit Card,2022-04-11,unspecified,4.0,wyzpguy@gmail.com,...,3,Pending,150,TRK1663,Delhi,20-06-2022,20311.041319,Fashion,note1,81239.165275
13,100658,1003,44,Laptop,2.000000e+06,UPI,2020-05-12,unspecified,4.0,hdhzitl@gmail.com,...,1,Pending,100,NaN,Chennai,13/02/21,15423.711561,Accessories,note1,61644.846242
20,100496,1127,169,Headphones,2.000000e+06,Debit Card,2024-08-24,Chennai,2.0,biokraq@gmail.com,...,3,Delivered,50,TRK4913,Bengaluru,12-10-2018,10886.538161,Fashion,temp,21723.076323
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4855,101534,1153,13,Headphones,7.668544e+02,Cash,NaN,Mumbai,4.0,ysqrxbq@yahoo.com,...,1,Delivered,100,TRK2416,Bengaluru,2022/01/03,43434.001308,Accessories,NaN,173686.005231
4857,100575,1004,179,Mobile,2.000000e+06,Credit Card,2020-08-13,Bengaluru,5.0,kcnkctv@hotmail.com,...,1,Pending,100,TRK4843,Chennai,08-12-2023,37538.792046,Electronics,NaN,187643.960229
4874,100053,1039,187,Laptop,2.380147e+04,Credit Card,NaN,Bengaluru,5.0,bdwuiis@gmail.com,...,5,Cancelled,100,NaN,Chennai,17/03/19,9214.851110,Electronics,NaN,46069.255548
4905,100304,1091,99,Laptop,2.000000e+06,UPI,2021-10-18,Mumbai,2.0,nrfnrfg@hotmail.com,...,3,Pending,150,NaN,Mumbai,08/07/23,27592.992544,Electronics,note1,55165.985087
4984,100832,1064,151,Mobile,8.000390e+04,Credit Card,2021-09-25,Chennai,5.0,hzggukg@gmal.com,...,3,Delivered,50,TRK1565,Chennai,23/12/21,29784.570278,Accessories,-,148917.851392

2.	Add Delivery_Duration = Delivery_Date − Order_Date

In [ ]:
a['Delivery_Date'] = pd.to_datetime(a['Delivery_Date'],errors='coerce')
a['Order_Date'] = pd.to_datetime(a['Order_Date'],errors='coerce')
a['Delivery_Duration'] = a['Delivery_Date'] - a['Order_Date']
a

/tmp/ipykernel_2327/1077903627.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  a['Delivery_Date'] = pd.to_datetime(a['Delivery_Date'],errors='coerce')

,Order_ID,Customer_ID,Product_ID,Product_Name,Order_Amount,Payment_Mode,Order_Date,Shipping_Address,Quantity,Email,...,Status,Shipping_Fee,Tracking_Number,Billing_Address,Delivery_Date,Price,Category,temp_notes,Total_Price,Delivery_Duration
0,101126,1179,102,Camera,7.322619e+04,Credit Card,2023-10-12,Delhi,5.0,fmflokr@gmail.com,...,Pending,150,NaN,Bengaluru,2020-08-13,30950.579179,Fashion,temp,154732.895897,-1155 days
4,101367,1128,145,Camera,8.156460e+04,Debit Card,2024-05-25,Hyderabad,3.0,srkahlm@yahoo.com,...,Delivered,100,NaN,Delhi,NaT,16394.129437,Accessories,NaN,49132.388311,NaT
7,101496,1189,138,Laptop,6.480424e+04,Credit Card,2022-04-11,unspecified,4.0,wyzpguy@gmail.com,...,Pending,150,TRK1663,Delhi,2022-06-20,20311.041319,Fashion,note1,81239.165275,70 days
13,100658,1003,44,Laptop,2.000000e+06,UPI,2020-05-12,unspecified,4.0,hdhzitl@gmail.com,...,Pending,100,NaN,Chennai,NaT,15423.711561,Accessories,note1,61644.846242,NaT
20,100496,1127,169,Headphones,2.000000e+06,Debit Card,2024-08-24,Chennai,2.0,biokraq@gmail.com,...,Delivered,50,TRK4913,Bengaluru,2018-10-12,10886.538161,Fashion,temp,21723.076323,-2143 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4855,101534,1153,13,Headphones,7.668544e+02,Cash,NaT,Mumbai,4.0,ysqrxbq@yahoo.com,...,Delivered,100,TRK2416,Bengaluru,NaT,43434.001308,Accessories,NaN,173686.005231,NaT
4857,100575,1004,179,Mobile,2.000000e+06,Credit Card,2020-08-13,Bengaluru,5.0,kcnkctv@hotmail.com,...,Pending,100,TRK4843,Chennai,2023-12-08,37538.792046,Electronics,NaN,187643.960229,1212 days
4874,100053,1039,187,Laptop,2.380147e+04,Credit Card,NaT,Bengaluru,5.0,bdwuiis@gmail.com,...,Cancelled,100,NaN,Chennai,NaT,9214.851110,Electronics,NaN,46069.255548,NaT
4905,100304,1091,99,Laptop,2.000000e+06,UPI,2021-10-18,Mumbai,2.0,nrfnrfg@hotmail.com,...,Pending,150,NaN,Mumbai,NaT,27592.992544,Electronics,note1,55165.985087,NaT
4984,100832,1064,151,Mobile,8.000390e+04,Credit Card,2021-09-25,Chennai,5.0,hzggukg@gmal.com,...,Delivered,50,TRK1565,Chennai,NaT,29784.570278,Accessories,-,148917.851392,NaT

3.	Create High_Value_Flag for orders > threshold

In [ ]:
threshold = 10000
for i in a.index :
  if a.loc[i,'Order_Amount'] > threshold :
    a.loc[i,'High_Value_Flag'] = 'High'
  else :
    a.loc[i,'High_Value_Flag'] = 'Low'
a[['Order_Amount','High_Value_Flag']]

      Order_Amount High_Value_Flag
0     7.322619e+04            High
4     8.156460e+04            High
7     6.480424e+04            High
13    2.000000e+06            High
20    2.000000e+06            High
...            ...             ...
4855  7.668544e+02             Low
4857  2.000000e+06            High
4874  2.380147e+04            High
4905  2.000000e+06            High
4984  8.000390e+04            High

[491 rows x 2 columns]

4.	Extract Order_Year, Order_Month.

In [ ]:
a['Year'] = a['Order_Date'].dt.year
a['Month']= a['Order_Date'].dt.month
a

,Order_ID,Customer_ID,Product_ID,Product_Name,Order_Amount,Payment_Mode,Order_Date,Shipping_Address,Quantity,Email,...,Billing_Address,Delivery_Date,Price,Category,temp_notes,Total_Price,Delivery_Duration,High_Value_Flag,Year,Month
0,101126,1179,102,Camera,7.322619e+04,Credit Card,2023-10-12,Delhi,5.0,fmflokr@gmail.com,...,Bengaluru,2020-08-13,30950.579179,Fashion,temp,154732.895897,-1155 days,High,2023.0,10.0
4,101367,1128,145,Camera,8.156460e+04,Debit Card,2024-05-25,Hyderabad,3.0,srkahlm@yahoo.com,...,Delhi,NaT,16394.129437,Accessories,NaN,49132.388311,NaT,High,2024.0,5.0
7,101496,1189,138,Laptop,6.480424e+04,Credit Card,2022-04-11,unspecified,4.0,wyzpguy@gmail.com,...,Delhi,2022-06-20,20311.041319,Fashion,note1,81239.165275,70 days,High,2022.0,4.0
13,100658,1003,44,Laptop,2.000000e+06,UPI,2020-05-12,unspecified,4.0,hdhzitl@gmail.com,...,Chennai,NaT,15423.711561,Accessories,note1,61644.846242,NaT,High,2020.0,5.0
20,100496,1127,169,Headphones,2.000000e+06,Debit Card,2024-08-24,Chennai,2.0,biokraq@gmail.com,...,Bengaluru,2018-10-12,10886.538161,Fashion,temp,21723.076323,-2143 days,High,2024.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4855,101534,1153,13,Headphones,7.668544e+02,Cash,NaT,Mumbai,4.0,ysqrxbq@yahoo.com,...,Bengaluru,NaT,43434.001308,Accessories,NaN,173686.005231,NaT,Low,NaN,NaN
4857,100575,1004,179,Mobile,2.000000e+06,Credit Card,2020-08-13,Bengaluru,5.0,kcnkctv@hotmail.com,...,Chennai,2023-12-08,37538.792046,Electronics,NaN,187643.960229,1212 days,High,2020.0,8.0
4874,100053,1039,187,Laptop,2.380147e+04,Credit Card,NaT,Bengaluru,5.0,bdwuiis@gmail.com,...,Chennai,NaT,9214.851110,Electronics,NaN,46069.255548,NaT,High,NaN,NaN
4905,100304,1091,99,Laptop,2.000000e+06,UPI,2021-10-18,Mumbai,2.0,nrfnrfg@hotmail.com,...,Mumbai,NaT,27592.992544,Electronics,note1,55165.985087,NaT,High,2021.0,10.0
4984,100832,1064,151,Mobile,8.000390e+04,Credit Card,2021-09-25,Chennai,5.0,hzggukg@gmal.com,...,Chennai,NaT,29784.570278,Accessories,-,148917.851392,NaT,High,2021.0,9.0

5.	Normalize Product_Name (strip, title case).

In [ ]:
a['Product_Name'].str.strip()
a['Product_Name'].str.title()
a

,Order_ID,Customer_ID,Product_ID,Product_Name,Order_Amount,Payment_Mode,Order_Date,Shipping_Address,Quantity,Email,...,Billing_Address,Delivery_Date,Price,Category,temp_notes,Total_Price,Delivery_Duration,High_Value_Flag,Year,Month
0,101126,1179,102,Camera,7.322619e+04,Credit Card,2023-10-12,Delhi,5.0,fmflokr@gmail.com,...,Bengaluru,2020-08-13,30950.579179,Fashion,temp,154732.895897,-1155 days,High,2023.0,10.0
4,101367,1128,145,Camera,8.156460e+04,Debit Card,2024-05-25,Hyderabad,3.0,srkahlm@yahoo.com,...,Delhi,NaT,16394.129437,Accessories,NaN,49132.388311,NaT,High,2024.0,5.0
7,101496,1189,138,Laptop,6.480424e+04,Credit Card,2022-04-11,unspecified,4.0,wyzpguy@gmail.com,...,Delhi,2022-06-20,20311.041319,Fashion,note1,81239.165275,70 days,High,2022.0,4.0
13,100658,1003,44,Laptop,2.000000e+06,UPI,2020-05-12,unspecified,4.0,hdhzitl@gmail.com,...,Chennai,NaT,15423.711561,Accessories,note1,61644.846242,NaT,High,2020.0,5.0
20,100496,1127,169,Headphones,2.000000e+06,Debit Card,2024-08-24,Chennai,2.0,biokraq@gmail.com,...,Bengaluru,2018-10-12,10886.538161,Fashion,temp,21723.076323,-2143 days,High,2024.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4855,101534,1153,13,Headphones,7.668544e+02,Cash,NaT,Mumbai,4.0,ysqrxbq@yahoo.com,...,Bengaluru,NaT,43434.001308,Accessories,NaN,173686.005231,NaT,Low,NaN,NaN
4857,100575,1004,179,Mobile,2.000000e+06,Credit Card,2020-08-13,Bengaluru,5.0,kcnkctv@hotmail.com,...,Chennai,2023-12-08,37538.792046,Electronics,NaN,187643.960229,1212 days,High,2020.0,8.0
4874,100053,1039,187,Laptop,2.380147e+04,Credit Card,NaT,Bengaluru,5.0,bdwuiis@gmail.com,...,Chennai,NaT,9214.851110,Electronics,NaN,46069.255548,NaT,High,NaN,NaN
4905,100304,1091,99,Laptop,2.000000e+06,UPI,2021-10-18,Mumbai,2.0,nrfnrfg@hotmail.com,...,Mumbai,NaT,27592.992544,Electronics,note1,55165.985087,NaT,High,2021.0,10.0
4984,100832,1064,151,Mobile,8.000390e+04,Credit Card,2021-09-25,Chennai,5.0,hzggukg@gmal.com,...,Chennai,NaT,29784.570278,Accessories,-,148917.851392,NaT,High,2021.0,9.0

6.	Create Customer_Lifetime_Value (sum of orders).

In [ ]:
a.groupby('Customer_ID')['Order_Amount'].sum()

Customer_ID
1000    6.000000e+06
1001    2.002860e+06
1002    2.098762e+06
1003    6.026141e+06
1004    6.208329e+06
            ...
1194    6.184475e+06
1196    2.018045e+06
1197    2.000000e+06
1198    4.144749e+06
1199    2.098658e+06
Name: Order_Amount, Length: 182, dtype: float64

7.	Convert emails to lowercase

In [ ]:
a['Email'].str.lower()

0         fmflokr@gmail.com
4         srkahlm@yahoo.com
7         wyzpguy@gmail.com
13        hdhzitl@gmail.com
20        biokraq@gmail.com
               ...
4855      ysqrxbq@yahoo.com
4857    kcnkctv@hotmail.com
4874      bdwuiis@gmail.com
4905    nrfnrfg@hotmail.com
4984       hzggukg@gmal.com
Name: Email, Length: 491, dtype: object

8.	Add Is_Returned flag based on  returns table

In [ ]:
for i in a.index :
  if a.loc[i,'Status'] == 'Returned' :
    a.loc[i,'Is_Returned'] = 'Yes'
  else :
    a.loc[i,'Is_Returned'] = 'No'
print(a[['Status','Is_Returned']])

         Status Is_Returned
0       Pending          No
4     Delivered          No
7       Pending          No
13      Pending          No
20    Delivered          No
...         ...         ...
4855  Delivered          No
4857    Pending          No
4874  Cancelled          No
4905    Pending          No
4984  Delivered          No

[491 rows x 2 columns]

9.	Standardize Payment_Mode categories

In [ ]:
a['Payment_Mode'] = a['Payment_Mode'].str.upper()
a

,Order_ID,Customer_ID,Product_ID,Product_Name,Order_Amount,Payment_Mode,Order_Date,Shipping_Address,Quantity,Email,...,Delivery_Date,Price,Category,temp_notes,Total_Price,Delivery_Duration,High_Value_Flag,Year,Month,Is_Returned
0,101126,1179,102,Camera,7.322619e+04,CREDIT CARD,2023-10-12,Delhi,5.0,fmflokr@gmail.com,...,2020-08-13,30950.579179,Fashion,temp,154732.895897,-1155 days,High,2023.0,10.0,No
4,101367,1128,145,Camera,8.156460e+04,DEBIT CARD,2024-05-25,Hyderabad,3.0,srkahlm@yahoo.com,...,NaT,16394.129437,Accessories,NaN,49132.388311,NaT,High,2024.0,5.0,No
7,101496,1189,138,Laptop,6.480424e+04,CREDIT CARD,2022-04-11,unspecified,4.0,wyzpguy@gmail.com,...,2022-06-20,20311.041319,Fashion,note1,81239.165275,70 days,High,2022.0,4.0,No
13,100658,1003,44,Laptop,2.000000e+06,UPI,2020-05-12,unspecified,4.0,hdhzitl@gmail.com,...,NaT,15423.711561,Accessories,note1,61644.846242,NaT,High,2020.0,5.0,No
20,100496,1127,169,Headphones,2.000000e+06,DEBIT CARD,2024-08-24,Chennai,2.0,biokraq@gmail.com,...,2018-10-12,10886.538161,Fashion,temp,21723.076323,-2143 days,High,2024.0,8.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4855,101534,1153,13,Headphones,7.668544e+02,CASH,NaT,Mumbai,4.0,ysqrxbq@yahoo.com,...,NaT,43434.001308,Accessories,NaN,173686.005231,NaT,Low,NaN,NaN,No
4857,100575,1004,179,Mobile,2.000000e+06,CREDIT CARD,2020-08-13,Bengaluru,5.0,kcnkctv@hotmail.com,...,2023-12-08,37538.792046,Electronics,NaN,187643.960229,1212 days,High,2020.0,8.0,No
4874,100053,1039,187,Laptop,2.380147e+04,CREDIT CARD,NaT,Bengaluru,5.0,bdwuiis@gmail.com,...,NaT,9214.851110,Electronics,NaN,46069.255548,NaT,High,NaN,NaN,No
4905,100304,1091,99,Laptop,2.000000e+06,UPI,2021-10-18,Mumbai,2.0,nrfnrfg@hotmail.com,...,NaT,27592.992544,Electronics,note1,55165.985087,NaT,High,2021.0,10.0,No
4984,100832,1064,151,Mobile,8.000390e+04,CREDIT CARD,2021-09-25,Chennai,5.0,hzggukg@gmal.com,...,NaT,29784.570278,Accessories,-,148917.851392,NaT,High,2021.0,9.0,No

10.	Remove extra spaces across text columns.

In [ ]:
a.columns = a.columns.str.strip()
a

,Order_ID,Customer_ID,Product_ID,Product_Name,Order_Amount,Payment_Mode,Order_Date,Shipping_Address,Quantity,Email,...,Delivery_Date,Price,Category,temp_notes,Total_Price,Delivery_Duration,High_Value_Flag,Year,Month,Is_Returned
0,101126,1179,102,Camera,7.322619e+04,CREDIT CARD,2023-10-12,Delhi,5.0,fmflokr@gmail.com,...,2020-08-13,30950.579179,Fashion,temp,154732.895897,-1155 days,High,2023.0,10.0,No
4,101367,1128,145,Camera,8.156460e+04,DEBIT CARD,2024-05-25,Hyderabad,3.0,srkahlm@yahoo.com,...,NaT,16394.129437,Accessories,NaN,49132.388311,NaT,High,2024.0,5.0,No
7,101496,1189,138,Laptop,6.480424e+04,CREDIT CARD,2022-04-11,unspecified,4.0,wyzpguy@gmail.com,...,2022-06-20,20311.041319,Fashion,note1,81239.165275,70 days,High,2022.0,4.0,No
13,100658,1003,44,Laptop,2.000000e+06,UPI,2020-05-12,unspecified,4.0,hdhzitl@gmail.com,...,NaT,15423.711561,Accessories,note1,61644.846242,NaT,High,2020.0,5.0,No
20,100496,1127,169,Headphones,2.000000e+06,DEBIT CARD,2024-08-24,Chennai,2.0,biokraq@gmail.com,...,2018-10-12,10886.538161,Fashion,temp,21723.076323,-2143 days,High,2024.0,8.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4855,101534,1153,13,Headphones,7.668544e+02,CASH,NaT,Mumbai,4.0,ysqrxbq@yahoo.com,...,NaT,43434.001308,Accessories,NaN,173686.005231,NaT,Low,NaN,NaN,No
4857,100575,1004,179,Mobile,2.000000e+06,CREDIT CARD,2020-08-13,Bengaluru,5.0,kcnkctv@hotmail.com,...,2023-12-08,37538.792046,Electronics,NaN,187643.960229,1212 days,High,2020.0,8.0,No
4874,100053,1039,187,Laptop,2.380147e+04,CREDIT CARD,NaT,Bengaluru,5.0,bdwuiis@gmail.com,...,NaT,9214.851110,Electronics,NaN,46069.255548,NaT,High,NaN,NaN,No
4905,100304,1091,99,Laptop,2.000000e+06,UPI,2021-10-18,Mumbai,2.0,nrfnrfg@hotmail.com,...,NaT,27592.992544,Electronics,note1,55165.985087,NaT,High,2021.0,10.0,No
4984,100832,1064,151,Mobile,8.000390e+04,CREDIT CARD,2021-09-25,Chennai,5.0,hzggukg@gmal.com,...,NaT,29784.570278,Accessories,-,148917.851392,NaT,High,2021.0,9.0,No

F. Sorting / Ranking / Aggregation

1.	Top 10 products by sales volume

In [ ]:
a.groupby('Product_ID')['Quantity'].sum().sort_values(ascending=False).head(10)

Product_ID
18     28.0
180    23.0
170    23.0
124    23.0
190    22.0
96     20.0
58     18.0
147    17.0
46     17.0
187    17.0
Name: Quantity, dtype: float64

2.	Top 10 customers by revenue

In [ ]:
a.groupby('Customer_ID')['Order_Amount'].sum().sort_values(ascending=False).head(10)

Customer_ID
1012    1.006082e+07
1015    8.203287e+06
1163    8.191178e+06
1098    8.027404e+06
1188    8.002486e+06
1103    8.000000e+06
1139    8.000000e+06
1137    8.000000e+06
1004    6.208329e+06
1194    6.184475e+06
Name: Order_Amount, dtype: float64

3.	Total revenue per month.

In [ ]:
a.groupby('Month')['Order_Amount'].sum()

Month
1.0     5.299030e+07
2.0     3.866252e+07
3.0     2.269196e+07
4.0     4.674920e+07
5.0     3.484661e+07
6.0     4.250780e+07
7.0     3.093943e+07
8.0     4.350546e+07
9.0     3.514019e+07
10.0    5.730622e+07
11.0    2.879126e+07
12.0    4.064726e+07
Name: Order_Amount, dtype: float64

4.	Average delivery duration per city

In [ ]:
a.groupby('City')['Delivery_Duration'].mean()

City
Chennai     180 days 13:09:40.645161290
Delhi               -156 days +19:30:00
Mumbai       84 days 11:36:46.451612903
chennai    -44 days +16:33:06.206896552
Name: Delivery_Duration, dtype: timedelta64[ns]

5.	Most common payment mode

In [ ]:
a['Payment_Mode'].value_counts()

Payment_Mode
CREDIT CARD    197
UPI            117
DEBIT CARD      60
CASH            59
COD             58
Name: count, dtype: int64

7.	Revenue per country.

In [ ]:
a.groupby('Country')['Order_Amount'].sum()

Country
India    2.408008e+08
UK       1.020120e+08
USA      1.768734e+08
Name: Order_Amount, dtype: float64

8.	Average order value by customer segment

In [ ]:
a.groupby('Customer_ID')['Order_Amount'].mean()

Customer_ID
1000    2.000000e+06
1001    6.676201e+05
1002    6.995873e+05
1003    1.506535e+06
1004    1.034721e+06
            ...
1194    1.236895e+06
1196    1.009023e+06
1197    2.000000e+06
1198    8.289498e+05
1199    1.049329e+06
Name: Order_Amount, Length: 182, dtype: float64

9.	Orders per day of week

In [ ]:
a['Day'] = a['Order_Date'].dt.day
a.groupby('Day')['Order_Amount'].sum()

Day
1.0     1.647397e+07
2.0     2.221509e+07
3.0     2.420516e+07
4.0     1.252894e+07
5.0     1.230348e+07
6.0     1.027348e+07
7.0     1.646511e+07
8.0     1.086100e+07
9.0     1.629036e+07
10.0    2.030095e+07
11.0    1.635491e+07
12.0    8.493821e+06
13.0    1.848822e+07
14.0    1.442427e+07
15.0    6.269801e+06
16.0    1.636320e+07
17.0    1.049944e+07
18.0    1.019715e+07
19.0    2.408521e+07
20.0    1.443428e+07
21.0    1.245600e+07
22.0    2.411184e+07
23.0    2.242972e+07
24.0    1.422992e+07
25.0    1.231491e+07
26.0    1.241502e+07
27.0    2.039967e+07
28.0    1.819708e+07
29.0    1.429485e+07
30.0    8.080664e+06
31.0    1.432070e+07
Name: Order_Amount, dtype: float64

10.	Quantity sold per category.

In [ ]:
a.groupby('Category')['Quantity'].sum()

Category
Accessories    472.0
Electronics    519.0
Fashion        472.0
Name: Quantity, dtype: float64

G. Advanced Cleaning & Validation

1.	Detect and standardize mixed Order_Date formats

In [ ]:
a['Order_Date'] = pd.to_datetime(a['Order_Date'],errors='coerce')

In [ ]:
a

,Order_ID,Customer_ID,Product_ID,Product_Name,Order_Amount,Payment_Mode,Order_Date,Shipping_Address,Quantity,Email,...,Price,Category,temp_notes,Total_Price,Delivery_Duration,High_Value_Flag,Year,Month,Is_Returned,Day
0,101126,1179,102,Camera,7.322619e+04,CREDIT CARD,2023-10-12,Delhi,5.0,fmflokr@gmail.com,...,30950.579179,Fashion,temp,154732.895897,-1155 days,High,2023.0,10.0,No,12.0
4,101367,1128,145,Camera,8.156460e+04,DEBIT CARD,2024-05-25,Hyderabad,3.0,srkahlm@yahoo.com,...,16394.129437,Accessories,NaN,49132.388311,NaT,High,2024.0,5.0,No,25.0
7,101496,1189,138,Laptop,6.480424e+04,CREDIT CARD,2022-04-11,unspecified,4.0,wyzpguy@gmail.com,...,20311.041319,Fashion,note1,81239.165275,70 days,High,2022.0,4.0,No,11.0
13,100658,1003,44,Laptop,2.000000e+06,UPI,2020-05-12,unspecified,4.0,hdhzitl@gmail.com,...,15423.711561,Accessories,note1,61644.846242,NaT,High,2020.0,5.0,No,12.0
20,100496,1127,169,Headphones,2.000000e+06,DEBIT CARD,2024-08-24,Chennai,2.0,biokraq@gmail.com,...,10886.538161,Fashion,temp,21723.076323,-2143 days,High,2024.0,8.0,No,24.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4855,101534,1153,13,Headphones,7.668544e+02,CASH,NaT,Mumbai,4.0,ysqrxbq@yahoo.com,...,43434.001308,Accessories,NaN,173686.005231,NaT,Low,NaN,NaN,No,NaN
4857,100575,1004,179,Mobile,2.000000e+06,CREDIT CARD,2020-08-13,Bengaluru,5.0,kcnkctv@hotmail.com,...,37538.792046,Electronics,NaN,187643.960229,1212 days,High,2020.0,8.0,No,13.0
4874,100053,1039,187,Laptop,2.380147e+04,CREDIT CARD,NaT,Bengaluru,5.0,bdwuiis@gmail.com,...,9214.851110,Electronics,NaN,46069.255548,NaT,High,NaN,NaN,No,NaN
4905,100304,1091,99,Laptop,2.000000e+06,UPI,2021-10-18,Mumbai,2.0,nrfnrfg@hotmail.com,...,27592.992544,Electronics,note1,55165.985087,NaT,High,2021.0,10.0,No,18.0
4984,100832,1064,151,Mobile,8.000390e+04,CREDIT CARD,2021-09-25,Chennai,5.0,hzggukg@gmal.com,...,29784.570278,Accessories,-,148917.851392,NaT,High,2021.0,9.0,No,25.0

3.	Identify customers with inconsistent contact details.

In [ ]:
a.groupby('Customer_ID')['Email'].value_counts()

Customer_ID  Email
1000         idwroya@yahoo.com      1
             oxbajyw@hotmail.com    1
             rbweigo@gmail.com      1
1001         kvekkne@hotmail.com    1
             noemail@ecom.com       1
                                   ..
1198         ousaawa@yahoo.com      1
             ozloyoa@hotmail.com    1
             yzlamym@gmal.com       1
1199         cdlphsh@gmal.com       1
             vnyplsc@gmal.com       1
Name: count, Length: 484, dtype: int64

In [ ]:
a['Payment_Mode'].unique()

array(['CREDIT CARD', 'DEBIT CARD', 'UPI', 'CASH', 'COD'], dtype=object)

5.	Validate Payment_Mode values against allowed list.

In [ ]:
List = ['UPI','Credit Card']
for i in a.index :
  V = a.loc[i,'Payment_Mode']
  if V in List :
    print(a.loc[i][['Payment_Mode']])

Payment_Mode    UPI
Name: 13, dtype: object
Payment_Mode    UPI
Name: 34, dtype: object
Payment_Mode    UPI
Name: 40, dtype: object
Payment_Mode    UPI
Name: 51, dtype: object
Payment_Mode    UPI
Name: 66, dtype: object
Payment_Mode    UPI
Name: 67, dtype: object
Payment_Mode    UPI
Name: 71, dtype: object
Payment_Mode    UPI
Name: 94, dtype: object
Payment_Mode    UPI
Name: 139, dtype: object
Payment_Mode    UPI
Name: 141, dtype: object
Payment_Mode    UPI
Name: 142, dtype: object
Payment_Mode    UPI
Name: 234, dtype: object
Payment_Mode    UPI
Name: 239, dtype: object
Payment_Mode    UPI
Name: 245, dtype: object
Payment_Mode    UPI
Name: 263, dtype: object
Payment_Mode    UPI
Name: 270, dtype: object
Payment_Mode    UPI
Name: 305, dtype: object
Payment_Mode    UPI
Name: 306, dtype: object
Payment_Mode    UPI
Name: 355, dtype: object
Payment_Mode    UPI
Name: 358, dtype: object
Payment_Mode    UPI
Name: 362, dtype: object
Payment_Mode    UPI
Name: 367, dtype: object
Payment_Mode    UPI
Name: 378, dtype: object
Payment_Mode    UPI
Name: 383, dtype: object
Payment_Mode    UPI
Name: 389, dtype: object
Payment_Mode    UPI
Name: 405, dtype: object
Payment_Mode    UPI
Name: 436, dtype: object
Payment_Mode    UPI
Name: 510, dtype: object
Payment_Mode    UPI
Name: 514, dtype: object
Payment_Mode    UPI
Name: 529, dtype: object
Payment_Mode    UPI
Name: 538, dtype: object
Payment_Mode    UPI
Name: 568, dtype: object
Payment_Mode    UPI
Name: 603, dtype: object
Payment_Mode    UPI
Name: 616, dtype: object
Payment_Mode    UPI
Name: 626, dtype: object
Payment_Mode    UPI
Name: 674, dtype: object
Payment_Mode    UPI
Name: 686, dtype: object
Payment_Mode    UPI
Name: 694, dtype: object
Payment_Mode    UPI
Name: 717, dtype: object
Payment_Mode    UPI
Name: 722, dtype: object
Payment_Mode    UPI
Name: 763, dtype: object
Payment_Mode    UPI
Name: 835, dtype: object
Payment_Mode    UPI
Name: 838, dtype: object
Payment_Mode    UPI
Name: 866, dtype: object
Payment_Mode    UPI
Name: 877, dtype: object
Payment_Mode    UPI
Name: 903, dtype: object
Payment_Mode    UPI
Name: 906, dtype: object
Payment_Mode    UPI
Name: 954, dtype: object
Payment_Mode    UPI
Name: 961, dtype: object
Payment_Mode    UPI
Name: 995, dtype: object
Payment_Mode    UPI
Name: 1000, dtype: object
Payment_Mode    UPI
Name: 1013, dtype: object
Payment_Mode    UPI
Name: 1027, dtype: object
Payment_Mode    UPI
Name: 1061, dtype: object
Payment_Mode    UPI
Name: 1072, dtype: object
Payment_Mode    UPI
Name: 1087, dtype: object
Payment_Mode    UPI
Name: 1102, dtype: object
Payment_Mode    UPI
Name: 1127, dtype: object
Payment_Mode    UPI
Name: 1193, dtype: object
Payment_Mode    UPI
Name: 1213, dtype: object
Payment_Mode    UPI
Name: 1219, dtype: object
Payment_Mode    UPI
Name: 1278, dtype: object
Payment_Mode    UPI
Name: 1301, dtype: object
Payment_Mode    UPI
Name: 1314, dtype: object
Payment_Mode    UPI
Name: 1338, dtype: object
Payment_Mode    UPI
Name: 1348, dtype: object
Payment_Mode    UPI
Name: 1376, dtype: object
Payment_Mode    UPI
Name: 1385, dtype: object
Payment_Mode    UPI
Name: 1409, dtype: object
Payment_Mode    UPI
Name: 1412, dtype: object
Payment_Mode    UPI
Name: 1420, dtype: object
Payment_Mode    UPI
Name: 1537, dtype: object
Payment_Mode    UPI
Name: 1599, dtype: object
Payment_Mode    UPI
Name: 1625, dtype: object
Payment_Mode    UPI
Name: 1668, dtype: object
Payment_Mode    UPI
Name: 1725, dtype: object
Payment_Mode    UPI
Name: 1802, dtype: object
Payment_Mode    UPI
Name: 1886, dtype: object
Payment_Mode    UPI
Name: 1931, dtype: object
Payment_Mode    UPI
Name: 1962, dtype: object
Payment_Mode    UPI
Name: 1984, dtype: object
Payment_Mode    UPI
Name: 2022, dtype: object
Payment_Mode    UPI
Name: 2036, dtype: object
Payment_Mode    UPI
Name: 2095, dtype: object
Payment_Mode    UPI
Name: 2145, dtype: object
Payment_Mode    UPI
Name: 2189, dtype: object
Payment_Mode    UPI
Name: 2195, dtype: object
Payment_Mode    UPI
Name: 2218, dtype: object
Payment_Mode    UPI
Name: 2229, dtype: object
Payment_Mode    UPI
Name: 2257, dtype: object
Payment_Mode    UPI
Name: 2360, dtype: object
Payment_Mode    UPI
Name: 2391, dtype: object
Payment_Mode    UPI
Name: 2407, dtype: object
Payment_Mode    UPI
Name: 2544, dtype: object
Payment_Mode    UPI
Name: 2564, dtype: object
Payment_Mode    UPI
Name: 2596, dtype: object
Payment_Mode    UPI
Name: 2701, dtype: object
Payment_Mode    UPI
Name: 2719, dtype: object
Payment_Mode    UPI
Name: 3100, dtype: object
Payment_Mode    UPI
Name: 3113, dtype: object
Payment_Mode    UPI
Name: 3142, dtype: object
Payment_Mode    UPI
Name: 3210, dtype: object
Payment_Mode    UPI
Name: 3369, dtype: object
Payment_Mode    UPI
Name: 3411, dtype: object
Payment_Mode    UPI
Name: 3441, dtype: object
Payment_Mode    UPI
Name: 3536, dtype: object
Payment_Mode    UPI
Name: 3547, dtype: object
Payment_Mode    UPI
Name: 3647, dtype: object
Payment_Mode    UPI
Name: 3739, dtype: object
Payment_Mode    UPI
Name: 4061, dtype: object
Payment_Mode    UPI
Name: 4073, dtype: object
Payment_Mode    UPI
Name: 4233, dtype: object
Payment_Mode    UPI
Name: 4630, dtype: object
Payment_Mode    UPI
Name: 4643, dtype: object
Payment_Mode    UPI
Name: 4658, dtype: object
Payment_Mode    UPI
Name: 4784, dtype: object
Payment_Mode    UPI
Name: 4905, dtype: object

6.	Fix inconsistent category → product mappings

In [ ]:
a.groupby('Product_ID')['Category'].value_counts()

Product_ID  Category
10          Electronics    2
11          Electronics    2
            Fashion        2
12          Fashion        2
            Electronics    1
                          ..
197         Accessories    1
            Fashion        1
198         Fashion        1
199         Electronics    3
            Fashion        1
Name: count, Length: 328, dtype: int64

7.	Remove irrelevant columns (temp_notes).

In [ ]:
a= a.drop(columns='temp_notes')

In [ ]:
a

,Order_ID,Customer_ID,Product_ID,Product_Name,Order_Amount,Payment_Mode,Order_Date,Shipping_Address,Quantity,Email,...,Delivery_Date,Price,Category,Total_Price,Delivery_Duration,High_Value_Flag,Year,Month,Is_Returned,Day
0,101126,1179,102,Camera,7.322619e+04,CREDIT CARD,2023-10-12,Delhi,5.0,fmflokr@gmail.com,...,2020-08-13,30950.579179,Fashion,154732.895897,-1155 days,High,2023.0,10.0,No,12.0
4,101367,1128,145,Camera,8.156460e+04,DEBIT CARD,2024-05-25,Hyderabad,3.0,srkahlm@yahoo.com,...,NaT,16394.129437,Accessories,49132.388311,NaT,High,2024.0,5.0,No,25.0
7,101496,1189,138,Laptop,6.480424e+04,CREDIT CARD,2022-04-11,unspecified,4.0,wyzpguy@gmail.com,...,2022-06-20,20311.041319,Fashion,81239.165275,70 days,High,2022.0,4.0,No,11.0
13,100658,1003,44,Laptop,2.000000e+06,UPI,2020-05-12,unspecified,4.0,hdhzitl@gmail.com,...,NaT,15423.711561,Accessories,61644.846242,NaT,High,2020.0,5.0,No,12.0
20,100496,1127,169,Headphones,2.000000e+06,DEBIT CARD,2024-08-24,Chennai,2.0,biokraq@gmail.com,...,2018-10-12,10886.538161,Fashion,21723.076323,-2143 days,High,2024.0,8.0,No,24.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4855,101534,1153,13,Headphones,7.668544e+02,CASH,NaT,Mumbai,4.0,ysqrxbq@yahoo.com,...,NaT,43434.001308,Accessories,173686.005231,NaT,Low,NaN,NaN,No,NaN
4857,100575,1004,179,Mobile,2.000000e+06,CREDIT CARD,2020-08-13,Bengaluru,5.0,kcnkctv@hotmail.com,...,2023-12-08,37538.792046,Electronics,187643.960229,1212 days,High,2020.0,8.0,No,13.0
4874,100053,1039,187,Laptop,2.380147e+04,CREDIT CARD,NaT,Bengaluru,5.0,bdwuiis@gmail.com,...,NaT,9214.851110,Electronics,46069.255548,NaT,High,NaN,NaN,No,NaN
4905,100304,1091,99,Laptop,2.000000e+06,UPI,2021-10-18,Mumbai,2.0,nrfnrfg@hotmail.com,...,NaT,27592.992544,Electronics,55165.985087,NaT,High,2021.0,10.0,No,18.0
4984,100832,1064,151,Mobile,8.000390e+04,CREDIT CARD,2021-09-25,Chennai,5.0,hzggukg@gmal.com,...,NaT,29784.570278,Accessories,148917.851392,NaT,High,2021.0,9.0,No,25.0

8.	Convert all date columns to datetime and sort chronologically

In [ ]:
a['Order_Date'] = pd.to_datetime(a['Order_Date'],errors='coerce')
a['Delivery_Date'] = pd.to_datetime(a['Delivery_Date'],errors='coerce')
a = a.sort_values('Order_Date')
a

,Order_ID,Customer_ID,Product_ID,Product_Name,Order_Amount,Payment_Mode,Order_Date,Shipping_Address,Quantity,Email,...,Delivery_Date,Price,Category,Total_Price,Delivery_Duration,High_Value_Flag,Year,Month,Is_Returned,Day
209,101602,1151,127,Mobile,2.000000e+06,DEBIT CARD,2018-01-06,Delhi,2.0,enpaqma@yahoo.com,...,NaT,14894.602993,Accessories,29739.205987,NaT,High,2018.0,1.0,No,6.0
3806,100242,1114,52,Laptop,2.000000e+06,CREDIT CARD,2018-01-08,unspecified,3.0,fybyseb@gmail.com,...,NaT,18441.757098,Electronics,55275.271295,NaT,High,2018.0,1.0,No,8.0
1302,101266,1054,59,Headphones,2.000000e+06,CASH,2018-01-08,Mumbai,1.0,ghvwise@gmail.com,...,NaT,9557.296493,Electronics,9507.296493,NaT,High,2018.0,1.0,No,8.0
728,101715,1193,194,Laptop,2.000000e+06,CREDIT CARD,2018-01-14,unspecified,3.0,noemail@ecom.com,...,2023-01-24,48721.018333,Fashion,146113.054998,1836 days,High,2018.0,1.0,No,14.0
1293,100064,1053,193,Backpack,2.000000e+06,CASH,2018-01-19,Delhi,2.0,wlpixjn@gmal.com,...,2019-04-11,7427.956725,Electronics,14835.913449,447 days,High,2018.0,1.0,No,19.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3698,100707,1152,25,Laptop,6.922771e+04,DEBIT CARD,NaT,Hyderabad,3.0,hoxsxey@gmail.com,...,NaT,28439.736243,Fashion,85269.208730,NaT,High,NaN,NaN,No,NaN
3709,101800,1096,191,Backpack,3.389170e+03,CREDIT CARD,NaT,Hyderabad,1.0,gqijlnl@hotmail.com,...,NaT,19859.352469,Fashion,19809.352469,NaT,Low,NaN,NaN,No,NaN
4253,100922,1179,36,Headphones,2.000000e+06,CREDIT CARD,NaT,Chennai,4.0,vudxpig@yahoo.com,...,NaT,15141.455107,Electronics,60515.820428,NaT,High,NaN,NaN,No,NaN
4855,101534,1153,13,Headphones,7.668544e+02,CASH,NaT,Mumbai,4.0,ysqrxbq@yahoo.com,...,NaT,43434.001308,Accessories,173686.005231,NaT,Low,NaN,NaN,No,NaN
4874,100053,1039,187,Laptop,2.380147e+04,CREDIT CARD,NaT,Bengaluru,5.0,bdwuiis@gmail.com,...,NaT,9214.851110,Electronics,46069.255548,NaT,High,NaN,NaN,No,NaN

9.	Detect  duplicated orders created by system errors

In [ ]:
a.duplicated(subset='Order_ID').sum()

np.int64(0)